/**
 * PRANAV CRACKERS - Multilingual Localization Module
 * Supported Languages: English (en), தமிழ் (ta), हिन्दी (hi), తెలుగు (te), മലയാളം (ml), ಕನ್ನಡ (kn)
 * Clean, professional translations without decorative emojis.
 */

const SUPPORTED_LANGUAGES = [
    { code: 'en', label: 'English', nativeName: 'English' },
    { code: 'ta', label: 'Tamil', nativeName: 'தமிழ்' },
    { code: 'hi', label: 'Hindi', nativeName: 'हिन्दी' },
    { code: 'te', label: 'Telugu', nativeName: 'తెలుగు' },
    { code: 'ml', label: 'Malayalam', nativeName: 'മലയാളം' },
    { code: 'kn', label: 'Kannada', nativeName: 'ಕನ್ನಡ' }
];

const TRANSLATIONS = {
    en: {
        navHome: 'Home',
        navProducts: 'Products',
        navGiftBoxes: 'Gift Boxes',
        navPriceList: 'Price List',
        navHowToOrder: 'How to Order',
        navAbout: 'About Us',
        navContact: 'Contact',
        navCart: 'My Requirement',
        navTrackOrder: 'Track Order',
        headerWhatsAppBtn: 'WhatsApp Us',

        heroTagline: 'Celebrate Brighter with PRANAV CRACKERS',
        heroSubtitle: 'Direct Sivakasi Crackers & Gift Boxes',
        heroLocation: 'Sivakasi, Tamil Nadu',
        heroPrimaryCta: 'View Products',
        heroSecondaryCta: 'View Gift Boxes',
        heroWhatsAppCta: 'WhatsApp Us',

        qaTitle: 'Quick Actions',
        qaProductsTitle: 'PRODUCTS',
        qaProductsDesc: 'Browse all fireworks & crackers',
        qaGiftBoxesTitle: 'GIFT BOXES',
        qaGiftBoxesDesc: 'Explore 5 ECHO City gift collections',
        qaPriceListTitle: 'PRICE LIST',
        qaPriceListDesc: 'View wholesale price catalogue',
        qaOrderTitle: 'MY REQUIREMENT',
        qaOrderDesc: 'View requirement list and submit',

        catSectionTitle: 'Product Categories',
        catSectionSubtitle: 'Choose from our extensive range of certified Sivakasi fireworks',
        viewProductsBtn: 'View Products',

        catalogSectionTitle: 'Our Fireworks Catalogue',
        catalogSearchHeading: 'What are you looking for?',
        catalogSearchPlaceholder: 'Search crackers (Sparklers, Pots, Rockets)...',
        filterAll: 'All Fireworks',
        viewDetailsBtn: 'View Details',
        addToCartBtn: 'Add to Requirement',
        addedToCartBtn: 'In Requirement',
        inCartLabel: 'in Requirement',
        repImageLabel: 'Representative Image',
        myRequirement: 'My Requirement',
        sendRequirement: 'SEND REQUIREMENT',
        continueAddingProducts: 'CONTINUE ADDING PRODUCTS',
        sendRequirementWhatsApp: 'SEND REQUIREMENT ON WHATSAPP',
        checkoutTitle: 'Customer Details',
        checkoutSubtitle: 'Enter your contact details to send your requirement on WhatsApp. Final product availability and pricing will be confirmed manually by PRANAV CRACKERS.',
        inStockLabel: 'Available',
        outOfStockLabel: 'Currently Unavailable',
        wholesalePriceTag: 'Wholesale Price',
        contactForPrice: 'Contact for Price',
        noProductsFound: 'No products found matching your search.',

        modalCategoryLabel: 'Category',
        modalPackSizeLabel: 'Pack Size',
        modalPriceLabel: 'Price',
        modalDescriptionLabel: 'Description',
        modalSafetyTip: 'Safety: Always light in open areas under adult supervision.',
        modalAddToCartBtn: 'Add to Cart',
        modalOrderNowBtn: 'Buy / Order Now',
        modalWhatsAppEnquiryBtn: 'WhatsApp Enquiry',
        modalRequestDiscountBtn: 'Request Discount',
        modalCloseBtn: 'Close',

        giftBoxSectionTitle: 'ECHO Gift Boxes – City Series',
        giftBoxSectionSubtitle: 'Official 5-box ECHO City Series Gift Box collection: Italy (35), Singapore (40), Dubai (50), Paris (60), Germany (70). Premium presentation boxes for family celebrations and wholesale gifting.',
        filterGiftAll: 'All Gift Boxes (5)',
        filterGift35_50: '35–50 Items',
        filterGift60_70: '60–70 Items',
        viewContentsBtn: 'View Contents',
        orderNowBtn: 'Order Now',
        whatsInsideHeading: "What's Inside?",
        tableColNo: 'No.',
        tableColProduct: 'Product Name',
        tableColQty: 'Quantity',
        boxContainsLabel: 'Included Varieties Breakdown:',
        compareGiftBoxesTitle: 'Compare All 5 ECHO Gift Boxes',
        compareGiftBoxesSubtitle: 'Compare item counts, highlights, and enquire directly.',

        priceListSectionTitle: 'PRICE LIST',
        priceListSectionSubtitle: 'PRANAV CRACKERS – Crackers & Gift Boxes',
        priceListSearchPlaceholder: 'Search products...',
        tableHeaderSNo: 'S.No.',
        tableHeaderItemName: 'Item Name',
        tableHeaderCompany: 'Company',
        tableHeaderPrice: 'Price (₹)',
        printPriceSheetBtn: 'Print / Save Price Sheet',
        whatsappPriceListBtn: 'WhatsApp Us',

        cartDrawerTitle: 'My Requirement',
        cartEmptyMsg: 'Your requirement list is currently empty. Browse products and click "Add to Requirement".',
        cartSummaryLabel: 'Estimated Catalogue Total:',
        cartTotalItems: 'Total Items:',
        proceedCheckoutBtn: 'Proceed to Submit Requirement',
        orderWhatsAppBtn: 'Send Requirement via WhatsApp',
        clearCartBtn: 'Clear List',
        cartHelperText: 'PRANAV CRACKERS will confirm product availability and final amount via WhatsApp before proceeding.',

        checkoutTitle: 'Submit Requirement & Delivery Details',
        checkoutSubtitle: 'Please enter your contact and delivery details to submit your requirement. Final amount confirmed via WhatsApp.',
        fieldName: 'Full Name *',
        fieldPhone: 'Mobile Number *',
        fieldAddress: 'Delivery Street Address *',
        fieldCity: 'City / Town *',
        fieldState: 'State *',
        fieldPincode: 'PIN Code *',
        fieldNotes: 'Additional Notes (Optional)',
        submitOrderBtn: 'Submit Requirement',
        cancelBtn: 'Cancel',

        orderReceivedTitle: 'REQUIREMENT RECEIVED',
        orderReceivedMsg: 'Your requirement has been received and is being reviewed by PRANAV CRACKERS.',
        orderNumberLabel: 'Reference Number:',
        orderStatusLabel: 'Status:',
        statusUnderReview: 'UNDER REVIEW',
        orderReviewNotice: 'Our team will confirm product availability, final quantity, pricing and details via WhatsApp.',
        chatWhatsAppOrderBtn: 'Send via WhatsApp',
        trackThisOrderBtn: 'Track This Order',

        discountModalTitle: 'Request Special Bulk Discount',
        discountModalSubtitle: 'Submit your requirement for review by our wholesale team. No automatic discount is applied.',
        discountCustomerName: 'Your Name *',
        discountCustomerPhone: 'Mobile Number *',
        discountItemsLabel: 'Selected Products for Discount *',
        discountMessage: 'Notes / Target Budget / Quantity Details *',
        sendDiscountRequestBtn: 'Send Discount Request',

        trackOrderTitle: 'Track Your Order',
        trackOrderSubtitle: 'Enter your Order Number (e.g. PC-2026-1001) or Mobile Number to check status and payment.',
        trackInputPlaceholder: 'Enter Order Number or Phone...',
        trackLookupBtn: 'Check Status',
        payNowBtn: 'Proceed to Pay',
        confirmPaymentBtn: 'Confirm Payment Made',

        howToOrderTitle: 'How to Order (Simple 3 Steps)',
        howToOrderSubtitle: 'Simple and transparent ordering process designed for everyone',
        step1Title: 'BROWSE & CART',
        step1Desc: 'Explore our fireworks catalogue and add items or gift boxes to your cart.',
        step2Title: 'SUBMIT ORDER',
        step2Desc: 'Enter delivery address and submit. Your order enters review.',
        step3Title: 'CONFIRM & PAY',
        step3Desc: 'Our Sivakasi team confirms availability and final payable amount before you pay.',

        aboutSectionTitle: 'About PRANAV CRACKERS',
        aboutDesc: 'PRANAV CRACKERS is committed to delivering quality fireworks directly from Sivakasi. We ensure honest wholesale pricing, reliable customer service, and verified celebrations for families and businesses.',
        value1Title: 'QUALITY',
        value1Desc: 'Carefully selected fireworks from trusted Sivakasi manufacturers.',
        value2Title: 'TRUST',
        value2Desc: 'Clear communication, authentic product weights, and transparent enquiries.',
        value3Title: 'CUSTOMER SATISFACTION',
        value3Desc: 'We focus on making every celebration bright, joyful, and hassle-free.',

        safetySectionTitle: 'Safety Guidelines',
        safetySectionSubtitle: 'Enjoy a joyful and safe festive celebration',
        safety1: 'Follow the instructions printed clearly on each product package.',
        safety2: 'Always light fireworks in open, well-ventilated outdoor areas away from obstacles.',
        safety3: 'Ensure children are always under responsible adult supervision.',
        safety4: 'Keep a bucket of water or sand readily available for safety.',
        safety5: 'Adhere to all applicable local laws, timings, and safety regulations.',

        contactSectionTitle: 'Contact PRANAV CRACKERS',
        contactSectionSubtitle: 'We are here to assist with your wholesale enquiries and festive requirements',
        contactLocationLabel: 'Wholesale Location',
        contactLocationVal: 'Sivakasi, Tamil Nadu, India',
        contactPhoneLabel: 'Phone & WhatsApp Numbers',
        callNowBtn: 'Call Now',

        footerTagline: 'Premium Fireworks • Wholesale',
        footerQuickLinksTitle: 'Quick Links',
        footerContactTitle: 'Contact Us',
        footerLegalNote: 'Notice: Sales, handling, and logistics strictly adhere to applicable Fireworks Acts, local safety laws, and statutory regulations. We do not support unlawful transit.',
        footerCopyright: '© 2026 PRANAV CRACKERS, Sivakasi. All Rights Reserved.',

        toastAdded: 'Added to your Cart',
        toastRemoved: 'Removed from cart',
        toastCleared: 'Cart cleared',
        toastOrderPlaced: 'Order placed successfully! Status: UNDER REVIEW',
        toastDiscountSent: 'Discount request submitted for review'
    },

    ta: {
        navHome: 'முகப்பு',
        navProducts: 'வெடிகள்',
        navGiftBoxes: 'கிஃப்ட் பாக்ஸ்',
        navPriceList: 'விலைப்பட்டியல்',
        navHowToOrder: 'ஆர்டர் முறை',
        navAbout: 'பற்றி',
        navContact: 'தொடர்பு',
        navCart: 'எனது தேவைப்பட்டியல்',
        navTrackOrder: 'ட்ராக்',
        headerWhatsAppBtn: 'வாட்ஸ்அப்',

        heroTagline: 'பிரணவ் கிராக்கர்ஸ் உடன் உங்கள் பண்டிகையை மேலும் பிரகாசமாக்குங்கள்',
        heroSubtitle: 'நேரடி சிவகாசி பட்டாசுகள் மற்றும் கிஃப்ட் பாக்ஸ்கள்',
        heroLocation: 'சிவகாசி, தமிழ்நாடு',
        heroPrimaryCta: 'வெடிகளை பார்க்க',
        heroSecondaryCta: 'கிஃப்ட் பாக்ஸ்கள்',
        heroWhatsAppCta: 'வாட்ஸ்அப்பில் தொடர்பு கொள்ள',

        qaTitle: 'விரைவு சேவைகள்',
        qaProductsTitle: 'பட்டாசுகள்',
        qaProductsDesc: 'அனைத்து வகை வெடிகளையும் காண்க',
        qaGiftBoxesTitle: 'கிஃப்ட் பாக்ஸ்கள்',
        qaGiftBoxesDesc: '5 எக்கோ சிட்டி கிஃப்ட் பாக்ஸ்கள்',
        qaPriceListTitle: 'விலைப்பட்டியல்',
        qaPriceListDesc: 'மொத்த விற்பனை விலைகளை காண்க',
        qaOrderTitle: 'எனது தேவைப்பட்டியல்',
        qaOrderDesc: 'தேர்வு செய்ததை சரிபார்த்து அனுப்ப',

        catSectionTitle: 'வெடி வகைகள்',
        catSectionSubtitle: 'சிவகாசியின் பிரத்யேக தரமான பட்டாசு வகைகளில் இருந்து தேர்வு செய்யுங்கள்',
        viewProductsBtn: 'வெடிகளை காண்க',

        catalogSectionTitle: 'எங்கள் பட்டாசு பட்டியல்',
        catalogSearchHeading: 'நீங்கள் என்ன தேடுகிறீர்கள்?',
        catalogSearchPlaceholder: 'வெடிகளைத் தேடுங்கள் (மத்தாப்பு, பூந்தொட்டி, ராக்கெட்)...',
        filterAll: 'அனைத்து வெடிகள்',
        viewDetailsBtn: 'முழு விவரம்',
        addToCartBtn: 'தேவைப்பட்டியலில் சேர்',
        addedToCartBtn: 'பட்டியலில் உள்ளது',
        inCartLabel: 'தேவைப்பட்டியலில்',
        repImageLabel: 'மாதிரி படம் (Representative)',
        myRequirement: 'எனது தேவைப்பட்டியல்',
        sendRequirement: 'தேவைப்பட்டியலை அனுப்பு',
        continueAddingProducts: 'மேலும் பட்டாசுகளை சேர்க்க',
        sendRequirementWhatsApp: 'வாட்ஸ்அப்பில் தேவையை அனுப்ப',
        checkoutTitle: 'வாடிக்கையாளர் விவரங்கள்',
        checkoutSubtitle: 'உங்கள் தேவையை வாட்ஸ்அப் மூலம் அனுப்ப விவரங்களை உள்ளிடவும். இறுதி விலை மற்றும் இருப்பு விவரம் உறுதி செய்யப்படும்.',
        inStockLabel: 'இருப்பில் உள்ளது',
        outOfStockLabel: 'தற்போது இருப்பில் இல்லை',
        wholesalePriceTag: 'மொத்த விலை',
        contactForPrice: 'விலை அறிய அழைக்கவும்',
        noProductsFound: 'தேடலுக்குரிய வெடிகள் கிடைக்கவில்லை.',

        modalCategoryLabel: 'வகை',
        modalPackSizeLabel: 'அளவு',
        modalPriceLabel: 'விலை',
        modalDescriptionLabel: 'விவரம்',
        modalSafetyTip: 'பாதுகாப்பு: பெரியவர்கள் முன்னிலையில் திறந்த வெளியில் மட்டுமே வெடிக்கவும்.',
        modalAddToCartBtn: 'கார்ட்டில் சேர்',
        modalOrderNowBtn: 'நேரடி ஆர்டர்',
        modalWhatsAppEnquiryBtn: 'வாட்ஸ்அப் தகவல்',
        modalRequestDiscountBtn: 'தள்ளுபடி கோரிக்கை',
        modalCloseBtn: 'மூடுக',

        giftBoxSectionTitle: 'அதிகாரப்பூர்வ கிஃப்ட் பாக்ஸ்கள்',
        giftBoxSectionSubtitle: '16 ரகங்கள் முதல் 70 ரகங்கள் வரை கொண்ட 9 பிரத்யேக தீபாவளி கிஃப்ட் பாக்ஸ்கள். குடும்ப கொண்டாட்டங்களுக்கும் மொத்த பரிசுகளுக்கும் ஏற்ற தொகுப்பு.',
        filterGiftAll: 'அனைத்து கிஃப்ட் பாக்ஸ்கள் (9)',
        filterGift16_30: '16–30 பொருட்கள்',
        filterGift35_50: '35–50 பொருட்கள்',
        filterGift60_70: '60–70 பொருட்கள்',
        viewContentsBtn: 'பொருட்களை காண்க',
        orderNowBtn: 'ஆர்டர் செய்க',
        whatsInsideHeading: "இதில் உள்ள வெடிகள் என்னென்ன?",
        tableColNo: 'எண்',
        tableColProduct: 'வெடி பெயர்',
        tableColQty: 'அளவு',
        boxContainsLabel: 'இதில் உள்ள வெடிகள் விவரம்:',
        compareGiftBoxesTitle: '9 கிஃப்ட் பாக்ஸ்களை ஒப்பிட',
        compareGiftBoxesSubtitle: 'பொருட்களின் எண்ணிக்கை மற்றும் விவரங்களை எளிதாக ஒப்பிடுங்கள்.',

        priceListSectionTitle: 'விலைப் பட்டியல்',
        priceListSectionSubtitle: 'பிரணவ் கிராக்கர்ஸ் – பட்டாசுகள் & கிஃப்ட் பாக்ஸ்கள்',
        priceListSearchPlaceholder: 'தயாரிப்புகளைத் தேடுங்கள்...',
        tableHeaderSNo: 'வ.எண்',
        tableHeaderItemName: 'பொருள் பெயர்',
        tableHeaderCompany: 'நிறுவனம்',
        tableHeaderPrice: 'விலை (₹)',
        printPriceSheetBtn: 'அச்சு / சேமிக்கவும்',
        whatsappPriceListBtn: 'வாட்ஸ்அப்',

        cartDrawerTitle: 'என் கார்ட் (Shopping Cart)',
        cartEmptyMsg: 'உங்கள் கார்ட் காலியாக உள்ளது. வெடிகளைப் பார்த்து "கார்ட்டில் சேர்" என்பதை அழுத்தவும்.',
        cartSummaryLabel: 'மதிப்பிடப்பட்ட மொத்த தொகை:',
        cartTotalItems: 'மொத்த பொருட்கள்:',
        proceedCheckoutBtn: 'முகவரி & ஆர்டர் செய்க',
        orderWhatsAppBtn: 'வாட்ஸ்அப்பில் ஆர்டர் அனுப்ப',
        clearCartBtn: 'கார்ட்டை அழிக்க',
        cartHelperText: 'பிரணவ் கிராக்கர்ஸ் உங்கள் ஆர்டரை உறுதி செய்த பிறகே கட்டணம் செலுத்த வேண்டும்.',

        checkoutTitle: 'முகவரி மற்றும் தொடர்பு விவரங்கள்',
        checkoutSubtitle: 'ஆர்டர் செய்ய உங்கள் பெயர், தொடர்பு எண் மற்றும் டெலிவரி முகவரியை உள்ளிடவும்.',
        fieldName: 'முழு பெயர் *',
        fieldPhone: 'கைபேசி எண் *',
        fieldAddress: 'முகவரி *',
        fieldCity: 'ஊர் / நகரம் *',
        fieldState: 'மாநிலம் *',
        fieldPincode: 'அஞ்சல் குறியீடு (PIN) *',
        fieldNotes: 'குறிப்புகள் (தேவைப்பட்டால்)',
        submitOrderBtn: 'ஆர்டரை சமர்ப்பிக்க (Review Pending)',
        cancelBtn: 'ரத்து செய்',

        orderReceivedTitle: 'ஆர்டர் பெறப்பட்டது (ORDER RECEIVED)',
        orderReceivedMsg: 'உங்கள் ஆர்டர் பெறப்பட்டு பிரணவ் கிராக்கர்ஸ் குழுவின் பரிசீலனையில் உள்ளது.',
        orderNumberLabel: 'ஆர்டர் எண்:',
        orderStatusLabel: 'நிலை:',
        statusUnderReview: 'பரிசீலனையில் (UNDER REVIEW)',
        orderReviewNotice: 'எங்கள் குழு வெடிகளின் இருப்பு, இறுதி அளவு மற்றும் கட்டண விவரங்களை உறுதி செய்யும்.',
        chatWhatsAppOrderBtn: 'வாட்ஸ்அப்பில் உறுதி செய்க',
        trackThisOrderBtn: 'ஆர்டர் நிலையை காண்க',

        discountModalTitle: 'சிறப்பு மொத்த தள்ளுபடி கோரிக்கை',
        discountModalSubtitle: 'உங்கள் மொத்த தேவையை சமர்ப்பிக்கவும். நிர்வாக குழு பரிசீலித்து முடிவு செய்யும்.',
        discountCustomerName: 'உங்கள் பெயர் *',
        discountCustomerPhone: 'கைபேசி எண் *',
        discountItemsLabel: 'தேவைப்படும் வெடிகள் *',
        discountMessage: 'எண்ணிக்கை மற்றும் குறிப்பு விவரங்கள் *',
        sendDiscountRequestBtn: 'கோரிக்கையை அனுப்ப',

        trackOrderTitle: 'ஆர்டர் நிலையை அறிய',
        trackOrderSubtitle: 'உங்கள் ஆர்டர் எண் அல்லது கைபேசி எண்ணை உள்ளிட்டு தற்போதைய நிலையை அறியவும்.',
        trackInputPlaceholder: 'ஆர்டர் எண் அல்லது போன் எண் உள்ளிடவும்...',
        trackLookupBtn: 'நிலையை பார்க்க',
        payNowBtn: 'கட்டணம் செலுத்த',
        confirmPaymentBtn: 'கட்டணம் செலுத்தியதை உறுதி செய்',

        howToOrderTitle: 'ஆர்டர் செய்வது எப்படி? (3 எளிய படிகள்)',
        howToOrderSubtitle: 'அனைவரும் எளிதில் புரியும் 3 எளிய படிகள்',
        step1Title: 'தேர்வு செய்க',
        step1Desc: 'எங்கள் பட்டியல் மற்றும் கிஃப்ட் பாக்ஸ்களில் இருந்து தேவையானதை கார்ட்டில் சேர்க்கவும்.',
        step2Title: 'முகவரி உள்ளிடவும்',
        step2Desc: 'உங்கள் முகவரியை உள்ளிட்டு ஆர்டரை சமர்ப்பிக்கவும்.',
        step3Title: 'உறுதி & கட்டணம்',
        step3Desc: 'எங்கள் குழு இருப்பை உறுதி செய்த பின்னர் கட்டண விவரம் பெற்று செலுத்தலாம்.',

        aboutSectionTitle: 'பிரணவ் கிராக்கர்ஸ் பற்றி',
        aboutDesc: 'பிரணவ் கிராக்கர்ஸ் சிவகாசியில் இருந்து தரமான பட்டாசுகளை நியாயமான விலையில் வழங்குகிறது. குடும்பங்களின் மகிழ்ச்சியான கொண்டாட்டத்திற்கு நாங்கள் உத்தரவாதம் அளிக்கிறோம்.',
        value1Title: 'தரம் (Quality)',
        value1Desc: 'கவனமாக தேர்ந்தெடுக்கப்பட்ட சிறந்த தரமான சிவகாசி பட்டாசுகள்.',
        value2Title: 'நம்பகத்தன்மை (Trust)',
        value2Desc: 'நேர்மையான தொடர்பாடல் மற்றும் வெளிப்படையான மொத்த விலை.',
        value3Title: 'வாடிக்கையாளர் திருப்தி',
        value3Desc: 'உங்கள் ஒவ்வொரு பண்டிகையையும் சிறப்பானதாக மாற்றுவதே எங்கள் நோக்கம்.',

        safetySectionTitle: 'பாதுகாப்பு வழிமுறைகள்',
        safetySectionSubtitle: 'பாதுகாப்பான மற்றும் மகிழ்ச்சியான தீபாவளி கொண்டாட்டத்திற்கு',
        safety1: 'ஒவ்வொரு பெட்டியிலும் அச்சிடப்பட்டுள்ள வழிமுறைகளை தவறாமல் படிக்கவும்.',
        safety2: 'பட்டாசுகளை எப்போதும் திறந்தவெளியில் மட்டுமே வெடிக்க வேண்டும்.',
        safety3: 'சிறுவர்கள் எப்போதும் பெரியவர்களின் பாதுகாப்பில் வெடிக்க வேண்டும்.',
        safety4: 'அருகில் ஒரு வாளி தண்ணீர் அல்லது மணல் தயாராக வைத்திருக்கவும்.',
        safety5: 'அனைத்து அரசு மற்றும் உள்ளூர் பாதுகாப்பு விதிமுறைகளை பின்பற்றவும்.',

        contactSectionTitle: 'பிரணவ் கிராக்கர்ஸ் தொடர்பு',
        contactSectionSubtitle: 'உங்கள் பட்டாசு தேவைகள் மற்றும் மொத்த ஆர்டர்களுக்கு எங்களை அணுகவும்',
        contactLocationLabel: 'விற்பனை மையம்',
        contactLocationVal: 'சிவகாசி, தமிழ்நாடு, இந்தியா',
        contactPhoneLabel: 'தொலைபேசி & வாட்ஸ்அப் எண்கள்',
        callNowBtn: 'அழைக்க',

        footerTagline: 'பிரீமியம் பட்டாசுகள் • மொத்த விற்பனை',
        footerQuickLinksTitle: 'முக்கிய இணைப்புகள்',
        footerContactTitle: 'தொடர்புக்கு',
        footerLegalNote: 'குறிப்பு: அனைத்து பட்டாசு விற்பனை மற்றும் கையாளுதல் சட்ட விதிகளுக்கு உட்பட்டது.',
        footerCopyright: '© 2026 பிரணவ் கிராக்கர்ஸ், சிவகாசி. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',

        toastAdded: 'கார்ட்டில் சேர்க்கப்பட்டது',
        toastRemoved: 'கார்ட்டில் இருந்து நீக்கப்பட்டது',
        toastCleared: 'கார்ட் அழிக்கப்பட்டது',
        toastOrderPlaced: 'ஆர்டர் சமர்ப்பிக்கப்பட்டது! நிலை: பரிசீலனையில் (UNDER REVIEW)',
        toastDiscountSent: 'தள்ளுபடி கோரிக்கை அனுப்பப்பட்டது'
    },

    hi: {
        navHome: 'होम',
        navProducts: 'पटाखे',
        navGiftBoxes: 'गिफ्ट बॉक्स',
        navPriceList: 'मूल्य सूची',
        navHowToOrder: 'ऑर्डर प्रक्रिया',
        navAbout: 'हमारे बारे में',
        navContact: 'संपर्क',
        navCart: 'मेरी आवश्यकता सूची',
        navTrackOrder: 'ट्रैक',
        headerWhatsAppBtn: 'व्हाट्सएप',

        heroTagline: 'प्रणव क्रैकर्स के साथ अपने त्योहारों को और रोशन बनाएं',
        heroSubtitle: 'सीधे शिवकाशी के पटाखे और गिफ्ट बॉक्स',
        heroLocation: 'शिवकाशी, तमिलनाडु',
        heroPrimaryCta: 'पटाखे देखें',
        heroSecondaryCta: 'गिफ्ट बॉक्स देखें',
        heroWhatsAppCta: 'व्हाट्सएप पर बात करें',

        qaTitle: 'त्वरित सेवाएं',
        qaProductsTitle: 'पटाखे',
        qaProductsDesc: 'सभी प्रकार के पटाखे देखें',
        qaGiftBoxesTitle: 'गिफ्ट बॉक्स',
        qaGiftBoxesDesc: '5 एको सिटी गिफ्ट बॉक्स',
        qaPriceListTitle: 'मूल्य सूची',
        qaPriceListDesc: 'थोक मूल्य सूची देखें',
        qaOrderTitle: 'मेरी आवश्यकता सूची',
        qaOrderDesc: 'सूची देखें और भेजें',

        catSectionTitle: 'पटाखा श्रेणियां',
        catSectionSubtitle: 'शिवकाशी के प्रमाणित और सर्वोत्तम पटाखों में से चुनें',
        viewProductsBtn: 'उत्पाद देखें',

        catalogSectionTitle: 'हमारा पटाखा कैटलॉग',
        catalogSearchHeading: 'आप क्या ढूंढ रहे हैं?',
        catalogSearchPlaceholder: 'पटाखे खोजें (फुलझड़ी, अनार, रॉकेट)...',
        filterAll: 'सभी पटाखे',
        viewDetailsBtn: 'विवरण देखें',
        addToCartBtn: 'आवश्यकता में जोड़ें',
        addedToCartBtn: 'सूची में जोड़ा गया',
        inCartLabel: 'आवश्यकता सूची में',
        repImageLabel: 'प्रतीकात्मक चित्र (Representative)',
        myRequirement: 'मेरी आवश्यकता सूची',
        sendRequirement: 'आवश्यकता भेजें',
        continueAddingProducts: 'और पटाखे जोड़ें',
        sendRequirementWhatsApp: 'व्हाट्सएप पर आवश्यकता भेजें',
        checkoutTitle: 'ग्राहक विवरण',
        checkoutSubtitle: 'व्हाट्सएप पर अपनी आवश्यकता भेजने के लिए विवरण दर्ज करें। अंतिम उपलब्धता और राशि की पुष्टि बाद में की जाएगी।',
        inStockLabel: 'उपलब्ध है',
        outOfStockLabel: 'वर्तमान में अनुपलब्ध',
        wholesalePriceTag: 'थोक मूल्य',
        contactForPrice: 'मूल्य हेतु संपर्क करें',
        noProductsFound: 'कोई पटाखा नहीं मिला।',

        modalCategoryLabel: 'श्रेणी',
        modalPackSizeLabel: 'पैक साइज',
        modalPriceLabel: 'कीमत',
        modalDescriptionLabel: 'विवरण',
        modalSafetyTip: 'सुरक्षा: हमेशा बड़ों की देखरेख में खुली जगह पर पटाखे जलाएं।',
        modalAddToCartBtn: 'कार्ट में जोड़ें',
        modalOrderNowBtn: 'अभी ऑर्डर करें',
        modalWhatsAppEnquiryBtn: 'व्हाट्सएप पूछताछ',
        modalRequestDiscountBtn: 'छूट का अनुरोध',
        modalCloseBtn: 'बंद करें',

        giftBoxSectionTitle: 'आधिकारिक दिवाली गिफ्ट बॉक्स',
        giftBoxSectionSubtitle: '16 से लेकर 70 आइटम तक के 9 विशेष गिफ्ट बॉक्स कलेक्शन। पारिवारिक उत्सव और थोक उपहार के लिए प्रीमियम पैकिंग।',
        filterGiftAll: 'सभी गिफ्ट बॉक्स (9)',
        filterGift16_30: '16–30 आइटम',
        filterGift35_50: '35–50 आइटम',
        filterGift60_70: '60–70 आइटम',
        viewContentsBtn: 'शामिल सामान देखें',
        orderNowBtn: 'ऑर्डर करें',
        whatsInsideHeading: "इसके अंदर क्या है?",
        tableColNo: 'क्र.',
        tableColProduct: 'पटाखे का नाम',
        tableColQty: 'मात्रा',
        boxContainsLabel: 'शामिल पटाखों की सूची:',
        compareGiftBoxesTitle: 'सभी 9 गिफ्ट बॉक्स की तुलना करें',
        compareGiftBoxesSubtitle: 'आइटम संख्या और मुख्य पटाखों की आसानी से तुलना करें।',

        priceListSectionTitle: 'मूल्य सूची',
        priceListSectionSubtitle: 'प्रणव क्रैकर्स – पटाखे और उपहार बक्से',
        priceListSearchPlaceholder: 'उत्पाद खोजें...',
        tableHeaderSNo: 'क्र.सं.',
        tableHeaderItemName: 'सामग्री का नाम',
        tableHeaderCompany: 'कंपनी',
        tableHeaderPrice: 'मूल्य (₹)',
        printPriceSheetBtn: 'प्रिंट / मूल्य सूची सहेजें',
        whatsappPriceListBtn: 'व्हाट्सएप करें',

        cartDrawerTitle: 'शॉपिंग कार्ट',
        cartEmptyMsg: 'आपकी कार्ट खाली है। उत्पाद देखकर "कार्ट में जोड़ें" पर क्लिक करें।',
        cartSummaryLabel: 'अनुमानित कुल राशि:',
        cartTotalItems: 'कुल आइटम:',
        proceedCheckoutBtn: 'पता भरें और ऑर्डर करें',
        orderWhatsAppBtn: 'व्हाट्सएप पर ऑर्डर भेजें',
        clearCartBtn: 'कार्ट खाली करें',
        cartHelperText: 'प्रणव क्रैकर्स द्वारा ऑर्डर पुष्टि के बाद ही भुगतान करना होगा।',

        checkoutTitle: 'डिलीवरी और संपर्क विवरण',
        checkoutSubtitle: 'ऑर्डर पूरा करने के लिए कृपया अपना नाम, मोबाइल नंबर और डिलीवरी पता दर्ज करें।',
        fieldName: 'पूरा नाम *',
        fieldPhone: 'मोबाइल नंबर *',
        fieldAddress: 'डिलीवरी का पता *',
        fieldCity: 'शहर / कस्बा *',
        fieldState: 'राज्य *',
        fieldPincode: 'पिन कोड *',
        fieldNotes: 'ऑर्डर नोट्स (वैकल्पिक)',
        submitOrderBtn: 'ऑर्डर सबमिट करें (समीक्षा लंबित)',
        cancelBtn: 'रद्द करें',

        orderReceivedTitle: 'ऑर्डर प्राप्त हुआ (ORDER RECEIVED)',
        orderReceivedMsg: 'आपका ऑर्डर प्राप्त हो गया है और प्रणव क्रैकर्स द्वारा समीक्षा की जा रही है।',
        orderNumberLabel: 'ऑर्डर संख्या:',
        orderStatusLabel: 'स्थिति:',
        statusUnderReview: 'समीक्षाधीन (UNDER REVIEW)',
        orderReviewNotice: 'हमारी टीम उपलब्धता, अंतिम मात्रा और मूल्य विवरण की पुष्टि करेगी।',
        chatWhatsAppOrderBtn: 'व्हाट्सएप पर बात करें',
        trackThisOrderBtn: 'ऑर्डर ट्रैक करें',

        discountModalTitle: 'थोक छूट के लिए अनुरोध',
        discountModalSubtitle: 'अपनी थोक आवश्यकता सबमिट करें। हमारी टीम समीक्षा करके निर्णय लेगी।',
        discountCustomerName: 'आपका नाम *',
        discountCustomerPhone: 'मोबाइल नंबर *',
        discountItemsLabel: 'चुने गए पटाखे *',
        discountMessage: 'मात्रा और बजट का विवरण *',
        sendDiscountRequestBtn: 'अनुरोध भेजें',

        trackOrderTitle: 'ऑर्डर स्थिति जानें',
        trackOrderSubtitle: 'ऑर्डर स्थिति और भुगतान विवरण देखने के लिए अपना ऑर्डर नंबर या मोबाइल नंबर दर्ज करें।',
        trackInputPlaceholder: 'ऑर्डर नंबर या फोन नंबर दर्ज करें...',
        trackLookupBtn: 'स्थिति देखें',
        payNowBtn: 'भुगतान करें',
        confirmPaymentBtn: 'भुगतान पुष्टि करें',

        howToOrderTitle: 'ऑर्डर कैसे करें (3 आसान चरण)',
        howToOrderSubtitle: 'सभी के लिए आसान और पारदर्शी ऑर्डर प्रक्रिया',
        step1Title: 'चुनें और कार्ट करें',
        step1Desc: 'कैटलॉग और गिफ्ट बॉक्स में से अपनी पसंद के पटाखे कार्ट में जोड़ें।',
        step2Title: 'पता दर्ज करें',
        step2Desc: 'डिलीवरी का पता भरकर ऑर्डर सबमिट करें।',
        step3Title: 'पुष्टि और भुगतान',
        step3Desc: 'हमारी टीम पुष्टि करेगी जिसके बाद आप सुरक्षित भुगतान कर सकते हैं।',

        aboutSectionTitle: 'प्रणव क्रैकर्स के बारे में',
        aboutDesc: 'प्रणव क्रैकर्स शिवकाशी से सीधे उच्च गुणवत्ता वाले पटाखे प्रदान करता है। हम उचित थोक मूल्य और प्रामाणिक सेवा सुनिश्चित करते हैं।',
        value1Title: 'गुणवत्ता (Quality)',
        value1Desc: 'शिवकाशी के शीर्ष निर्माताओं से चयनित बेहतरीन पटाखे।',
        value2Title: 'विश्वास (Trust)',
        value2Desc: 'पारदर्शी संचार और वास्तविक थोक मूल्य।',
        value3Title: 'ग्राहक संतुष्टि',
        value3Desc: 'आपके त्योहार को खुशियों से रोशन बनाना ही हमारा उद्देश्य है।',

        safetySectionTitle: 'सुरक्षा निर्देश',
        safetySectionSubtitle: 'सुरक्षित और आनंदमय दिवाली के लिए जरूरी नियम',
        safety1: 'प्रत्येक पैकेट पर मुद्रित निर्देशों का पालन करें।',
        safety2: 'पटाखों को हमेशा खुली हवादार जगह पर ही जलाएं।',
        safety3: 'बच्चे हमेशा बड़ों की देखरेख में ही पटाखे जलाएं।',
        safety4: 'पास में पानी या रेत की बाल्टी तैयार रखें।',
        safety5: 'सभी सरकारी व स्थानीय सुरक्षा नियमों का पालन करें।',

        contactSectionTitle: 'प्रणव क्रैकर्स से संपर्क करें',
        contactSectionSubtitle: 'थोक ऑर्डर और पूछताछ के लिए हमसे संपर्क करें',
        contactLocationLabel: 'बिक्री केंद्र',
        contactLocationVal: 'शिवकाशी, तमिलनाडु, भारत',
        contactPhoneLabel: 'फोन और व्हाट्सएप नंबर',
        callNowBtn: 'कॉल करें',

        footerTagline: 'प्रीमियम पटाखे • थोक बिक्री',
        footerQuickLinksTitle: 'त्वरित लिंक',
        footerContactTitle: 'संपर्क करें',
        footerLegalNote: 'सूचना: पटाखों की बिक्री और परिवहन सभी सरकारी सुरक्षा नियमों के अधीन है।',
        footerCopyright: '© 2026 प्रणव क्रैकर्स, शिवकाशी। सर्वाधिकार सुरक्षित।',

        toastAdded: 'कार्ट में जोड़ा गया',
        toastRemoved: 'कार्ट से हटाया गया',
        toastCleared: 'कार्ट खाली कर दी गई',
        toastOrderPlaced: 'ऑर्डर सबमिट हो गया! स्थिति: समीक्षाधीन',
        toastDiscountSent: 'छूट अनुरोध भेजा गया'
    },

    te: {
        navHome: 'హోమ్',
        navProducts: 'బాణసంచా',
        navGiftBoxes: 'గిఫ్ట్ బాక్స్',
        navPriceList: 'ధరల పట్టిక',
        navHowToOrder: 'ఆర్డర్ విధానం',
        navAbout: 'మా గురించి',
        navContact: 'సంప్రదించండి',
        navCart: 'నా అవసరాల జాబితా',
        navTrackOrder: 'ట్రాక్',
        headerWhatsAppBtn: 'వాట్సాప్',

        heroTagline: 'ప్రణవ్ క్రాకర్స్‌తో మీ పండుగను మరింత ప్రకాశవంతంగా జరుపుకోండి',
        heroSubtitle: 'శివకాశి నేరుగా టపాసులు & గిఫ్ట్ బాక్స్‌లు',
        heroLocation: 'శివకాశి, తమిళనాడు',
        heroPrimaryCta: 'టపాసులు చూడండి',
        heroSecondaryCta: 'గిఫ్ట్ బాక్స్‌లు',
        heroWhatsAppCta: 'వాట్సాప్‌లో మాట్లాడండి',

        qaTitle: 'త్వరిత సేవలు',
        qaProductsTitle: 'బాణసంచా',
        qaProductsDesc: 'అన్ని రకాల టపాసులను వీక్షించండి',
        qaGiftBoxesTitle: 'గిఫ్ట్ బాక్స్‌లు',
        qaGiftBoxesDesc: '5 ఎకో సిటీ గిఫ్ట్ బాక్స్‌లు',
        qaPriceListTitle: 'ధరల పట్టిక',
        qaPriceListDesc: 'హోల్‌సేల్ ధరల వివరాలు చూడండి',
        qaOrderTitle: 'నా అవసరాల జాబితా',
        qaOrderDesc: 'ఎంపిక చేసిన వాటిని పంపండి',

        catSectionTitle: 'టపాసుల రకాలు',
        catSectionSubtitle: 'శివకాశి నాణ్యమైన బాణసంచా రకాలను ఎంచుకోండి',
        viewProductsBtn: 'ఉత్పత్తులను చూడండి',

        catalogSectionTitle: 'మా బాణసంచా కేటలాగ్',
        catalogSearchHeading: 'మీరు దేని కోసం వెతుకుతున్నారు?',
        catalogSearchPlaceholder: 'టపాసులను శోధించండి (చిచ్చుబుడ్లు, కాకరపువ్వొత్తులు, రాకెట్లు)...',
        filterAll: 'అన్ని రకాలు',
        viewDetailsBtn: 'పూర్తి వివరాలు',
        addToCartBtn: 'జాబితాలో చేర్చండి',
        addedToCartBtn: 'జాబితాలో ఉంది',
        inCartLabel: 'జాబితాలో',
        repImageLabel: 'ప్రతినిధి చిత్రం (Representative)',
        myRequirement: 'నా అవసరాల జాబితా',
        sendRequirement: 'అవసరాల జాబితా పంపండి',
        continueAddingProducts: 'మరిన్ని టపాసులు జోడించండి',
        sendRequirementWhatsApp: 'వాట్సాప్‌లో జాబితా పంపండి',
        checkoutTitle: 'వినియోగదారు వివరాలు',
        checkoutSubtitle: 'మీ వివరాలను నమోదు చేసి వాట్సాప్‌లో పంపండి.',
        inStockLabel: 'అందుబాటులో ఉంది',
        outOfStockLabel: 'ప్రస్తుతం అందుబాటులో లేదు',
        wholesalePriceTag: 'హోల్‌సేల్ ధర',
        contactForPrice: 'ధర కోసం సంప్రదించండి',
        noProductsFound: 'ఎలాంటి టపాసులు కనుగొనబడలేదు.',

        modalCategoryLabel: 'రకం',
        modalPackSizeLabel: 'ప్యాక్ పరిమాణం',
        modalPriceLabel: 'ధర',
        modalDescriptionLabel: 'వివరణ',
        modalSafetyTip: 'భద్రత: పెద్దల పర్యవేక్షణలో మాత్రమే బహిరంగ ప్రదేశాల్లో కాల్చండి.',
        modalAddToCartBtn: 'కార్ట్‌లో చేర్చండి',
        modalOrderNowBtn: 'ఇప్పుడే ఆర్డర్ చేయండి',
        modalWhatsAppEnquiryBtn: 'వాట్సాప్ విచారణ',
        modalRequestDiscountBtn: 'డిస్కౌంట్ అభ్యర్థన',
        modalCloseBtn: 'మూసివేయి',

        giftBoxSectionTitle: 'అధికారిక గిఫ్ట్ బాక్స్‌లు',
        giftBoxSectionSubtitle: '16 నుండి 70 రకాల వరకు 9 ప్రత్యేక దీపావళి గిఫ్ట్ బాక్స్‌లు. కుటుంబాలకు మరియు బహుమతులకు అనువైన ప్యాకింగ్.',
        filterGiftAll: 'అన్ని గిఫ్ట్ బాక్స్‌లు (9)',
        filterGift16_30: '16–30 వస్తువులు',
        filterGift35_50: '35–50 వస్తువులు',
        filterGift60_70: '60–70 వస్తువులు',
        viewContentsBtn: 'వస్తువుల వివరాలు',
        orderNowBtn: 'ఆర్డర్ చేయండి',
        whatsInsideHeading: "ఇందులో ఉన్న టపాసులు ఏమిటి?",
        tableColNo: 'సంఖ్య',
        tableColProduct: 'టపాసు పేరు',
        tableColQty: 'పరిమాణం',
        boxContainsLabel: 'ఇందులో ఉన్న వస్తువుల వివరాలు:',
        compareGiftBoxesTitle: '9 గిఫ్ట్ బాక్స్‌లను పోల్చండి',
        compareGiftBoxesSubtitle: 'వస్తువుల సంఖ్య మరియు వివరాలను సులభంగా సరిపోల్చండి.',

        priceListSectionTitle: 'ధరల పట్టిక',
        priceListSectionSubtitle: 'ప్రణవ్ క్రాకర్స్ – బాణాసంచా & గిఫ్ట్ బాక్స్‌లు',
        priceListSearchPlaceholder: 'ఉత్పత్తులను వెతకండి...',
        tableHeaderSNo: 'వ.సంఖ్య',
        tableHeaderItemName: 'వస్తువు పేరు',
        tableHeaderCompany: 'కంపెనీ',
        tableHeaderPrice: 'ధర (₹)',
        printPriceSheetBtn: 'ప్రింట్ / ధరల షీట్ సేవ్ చేయండి',
        whatsappPriceListBtn: 'వాట్సాప్ చేయండి',

        cartDrawerTitle: 'నా కార్ట్ (Shopping Cart)',
        cartEmptyMsg: 'మీ కార్ట్ ఖాళీగా ఉంది. టపాసులను ఎంచుకుని "కార్ట్‌లో చేర్చండి" నొక్కండి.',
        cartSummaryLabel: 'అంచనా మొత్తం విలువ:',
        cartTotalItems: 'మొత్తం వస్తువులు:',
        proceedCheckoutBtn: 'చిరునామా & ఆర్డర్ చేయండి',
        orderWhatsAppBtn: 'వాట్సాప్‌లో ఆర్డర్ పంపండి',
        clearCartBtn: 'కార్ట్ ఖాళీ చేయండి',
        cartHelperText: 'ప్రణవ్ క్రాకర్స్ మీ ఆర్డర్‌ను ధృవీకరించిన తర్వాత మాత్రమే చెల్లింపు చేయాలి.',

        checkoutTitle: 'డెలివరీ మరియు సంప్రదింపు వివరాలు',
        checkoutSubtitle: 'ఆర్డర్ చేయడానికి మీ పేరు, ఫోన్ నంబర్ మరియు చిరునామాను నమోదు చేయండి.',
        fieldName: 'పూర్తి పేరు *',
        fieldPhone: 'మొబైల్ నంబర్ *',
        fieldAddress: 'డెలివరీ చిరునామా *',
        fieldCity: 'ఊరు / నగరం *',
        fieldState: 'రాష్ట్రం *',
        fieldPincode: 'పిన్ కోడ్ *',
        fieldNotes: 'ఆర్డర్ గమనికలు (ఐచ్ఛికం)',
        submitOrderBtn: 'ఆర్డర్ సమర్పించండి (Review Pending)',
        cancelBtn: 'రద్దు చేయండి',

        orderReceivedTitle: 'ఆర్డర్ స్వీకరించబడింది (ORDER RECEIVED)',
        orderReceivedMsg: 'మీ ఆర్డర్ స్వీకరించబడింది మరియు ప్రణవ్ క్రాకర్స్ బృందం పరిశీలనలో ఉంది.',
        orderNumberLabel: 'ఆర్డర్ నంబర్:',
        orderStatusLabel: 'స్థితి:',
        statusUnderReview: 'పరిశీలనలో ఉంది (UNDER REVIEW)',
        orderReviewNotice: 'మా బృందం వస్తువుల లభ్యత, తుది పరిమాణం మరియు ధర వివరాలను నిర్ధారిస్తుంది.',
        chatWhatsAppOrderBtn: 'వాట్సాప్‌లో మాట్లాడండి',
        trackThisOrderBtn: 'ఆర్డర్ ట్రాక్ చేయండి',

        discountModalTitle: 'ప్రత్యేక బల్క్ డిస్కౌంట్ అభ్యర్థన',
        discountModalSubtitle: 'మీ హోల్‌సేల్ అవసరాలను సమర్పించండి. మా బృందం పరిశీలించి నిర్ణయిస్తుంది.',
        discountCustomerName: 'మీ పేరు *',
        discountCustomerPhone: 'మొబైల్ నంబర్ *',
        discountItemsLabel: 'ఎంచుకున్న టపాసులు *',
        discountMessage: 'పరిమాణం మరియు బడ్జెట్ వివరాలు *',
        sendDiscountRequestBtn: 'అభ్యర్థన పంపండి',

        trackOrderTitle: 'ఆర్డర్ స్థితిని తెలుసుకోండి',
        trackOrderSubtitle: 'మీ ఆర్డర్ నంబర్ లేదా మొబైల్ నంబర్‌తో ప్రస్తుత స్థితిని తెలుసుకోండి.',
        trackInputPlaceholder: 'ఆర్డర్ నంబర్ లేదా ఫోన్ నంబర్ నమోదు చేయండి...',
        trackLookupBtn: 'స్థితిని చూడండి',
        payNowBtn: 'చెల్లింపు చేయండి',
        confirmPaymentBtn: 'చెల్లింపును ధృవీకరించండి',

        howToOrderTitle: 'ఆర్డర్ చేయడం ఎలా? (3 సులభమైన దశలు)',
        howToOrderSubtitle: 'అందరికీ అర్థమయ్యే సులభమైన ఆర్డర్ విధానం',
        step1Title: 'ఎంచుకోండి',
        step1Desc: 'కేటలాగ్ లేదా గిఫ్ట్ బాక్స్‌లలో కావలసిన టపాసులను కార్ట్‌లో చేర్చండి.',
        step2Title: 'చిరునామా ఇవ్వండి',
        step2Desc: 'డెలివరీ చిరునామా నమోదు చేసి ఆర్డర్ సబ్మిట్ చేయండి.',
        step3Title: 'నిర్ధారణ & చెల్లింపు',
        step3Desc: 'మా బృందం ధృవీకరించిన తర్వాత సురక్షితంగా చెల్లింపు చేయండి.',

        aboutSectionTitle: 'ప్రణవ్ క్రాకర్స్ గురించి',
        aboutDesc: 'ప్రణవ్ క్రాకర్స్ శివకాశి నుండి నేరుగా ఉత్తమ నాణ్యత గల బాణసంచాను సరసమైన ధరలకు అందిస్తుంది.',
        value1Title: 'నాణ్యత (Quality)',
        value1Desc: 'శివకాశి ప్రముఖ తయారీదారుల నుండి ఎంపిక చేసిన టపాసులు.',
        value2Title: 'నమ్మకం (Trust)',
        value2Desc: 'స్పష్టమైన సమాచారం మరియు నిజాయితీ గల హోల్‌సేల్ ధరలు.',
        value3Title: 'కస్టమర్ సంతృప్తి',
        value3Desc: 'మీ పండుగలను మరింత ఆనందదాయకంగా మార్చడమే మా లక్ష్యం.',

        safetySectionTitle: 'భద్రతా సూచనలు',
        safetySectionSubtitle: 'సురక్షితమైన మరియు సంతోషకరమైన దీపావళి కోసం',
        safety1: 'ప్రతి ప్యాకెట్‌పై ముద్రించిన సూచనలను తప్పక చదవండి.',
        safety2: 'టపాసులను ఎల్లప్పుడూ బహిరంగ ప్రదేశాల్లో మాత్రమే కాల్చాలి.',
        safety3: 'పిల్లలు ఎల్లప్పుడూ పెద్దల సమక్షంలోనే కాల్చాలి.',
        safety4: 'సమీపంలో బకెట్ నీరు లేదా ఇసుకను సిద్ధంగా ఉంచుకోండి.',
        safety5: 'ప్రభుత్వ మరియు భద్రతా నియమాలను పాటించండి.',

        contactSectionTitle: 'ప్రణవ్ క్రాకర్స్ సంప్రదింపులు',
        contactSectionSubtitle: 'మీ బాణసంచా అవసరాలు మరియు హోల్‌సేల్ ఆర్డర్ల కోసం మమ్మల్ని సంప్రదించండి',
        contactLocationLabel: 'విక్రయ కేంద్రం',
        contactLocationVal: 'శివకాశి, తమిళనాడు, భారతదేశం',
        contactPhoneLabel: 'ఫోన్ మరియు వాట్సాప్ నంబర్లు',
        callNowBtn: 'కాల్ చేయండి',

        footerTagline: 'ప్రీమియం బాణసంచా • హోల్‌సేల్',
        footerQuickLinksTitle: 'ముఖ్యమైన లింకులు',
        footerContactTitle: 'సంప్రదించండి',
        footerLegalNote: 'గమనిక: అమ్మకాలు మరియు రవాణా సంబంధిత చట్ట నిబంధనలకు లోబడి ఉంటాయి.',
        footerCopyright: '© 2026 ప్రణవ్ క్రాకర్స్, శివకాశి. సర్వహక్కులు ప్రత్యేకించబడ్డాయి.',

        toastAdded: 'కార్ట్‌లో చేర్చబడింది',
        toastRemoved: 'కార్ట్ నుండి తీసివేయబడింది',
        toastCleared: 'కార్ట్ ఖాళీ చేయబడింది',
        toastOrderPlaced: 'ఆర్డర్ సమర్పించబడింది! స్థితి: పరిశీలనలో ఉంది',
        toastDiscountSent: 'డిస్కౌంట్ అభ్యర్థన పంపబడింది'
    },

    ml: {
        navHome: 'ഹോം',
        navProducts: 'പടക്കങ്ങൾ',
        navGiftBoxes: 'ഗിഫ്റ്റ് ബോക്സ്',
        navPriceList: 'വിലവിവരം',
        navHowToOrder: 'ഓർഡർ രീതി',
        navAbout: 'ഞങ്ങളെക്കുറിച്ച്',
        navContact: 'ബന്ധപ്പെടുക',
        navCart: 'എന്റെ ആവശ്യങ്ങൾ',
        navTrackOrder: 'ട്രാക്ക്',
        headerWhatsAppBtn: 'വാട്ട്സ്ആപ്പ്',

        heroTagline: 'പ്രണവ് ക്രാക്കേഴ്സിനൊപ്പം നിങ്ങളുടെ ആഘോഷങ്ങൾ കൂടുതൽ തിളക്കമുള്ളതാക്കൂ',
        heroSubtitle: 'നേരിട്ട് ശിവകാശി പടക്കങ്ങളും ഗിഫ്റ്റ് ബോക്സുകളും',
        heroLocation: 'ശിവകാശി, തമിഴ്നാട്',
        heroPrimaryCta: 'പടക്കങ്ങൾ കാണുക',
        heroSecondaryCta: 'ഗിഫ്റ്റ് ബോക്സുകൾ',
        heroWhatsAppCta: 'വാട്ട്സ്ആപ്പിൽ സംസാരിക്കാം',

        qaTitle: 'പെട്ടെന്നുള്ള സേവനങ്ങൾ',
        qaProductsTitle: 'പടക്കങ്ങൾ',
        qaProductsDesc: 'എല്ലാത്തരം പടക്കങ്ങളും കാണുക',
        qaGiftBoxesTitle: 'ഗിഫ്റ്റ് ബോക്സുകൾ',
        qaGiftBoxesDesc: '5 എക്കോ സിറ്റി ഗിഫ്റ്റ് ബോക്സുകൾ',
        qaPriceListTitle: 'വിലവിവരം',
        qaPriceListDesc: 'മൊത്തവ്യാപാര നിരക്കുകൾ കാണുക',
        qaOrderTitle: 'എന്റെ ആവശ്യങ്ങൾ',
        qaOrderDesc: 'തിരഞ്ഞെടുത്തവ അയക്കുക',

        catSectionTitle: 'പടക്ക ഇനങ്ങൾ',
        catSectionSubtitle: 'ശിവകാശിയിലെ മികച്ച പടക്കങ്ങളിൽ നിന്ന് തിരഞ്ഞെടുക്കൂ',
        viewProductsBtn: 'ഇനങ്ങൾ കാണുക',

        catalogSectionTitle: 'ഞങ്ങളുടെ പടക്ക കാറ്റലോഗ്',
        catalogSearchHeading: 'നിങ്ങൾ എന്താണ് തിരയുന്നത്?',
        catalogSearchPlaceholder: 'പടക്കങ്ങൾ തിരയുക (പൂത്തിരി, മത്താപ്പ്, റോക്കറ്റ്)...',
        filterAll: 'എല്ലാ പടക്കങ്ങളും',
        viewDetailsBtn: 'പൂർണ്ണ വിവരങ്ങൾ',
        addToCartBtn: 'പട്ടികയിൽ ചേർക്കുക',
        addedToCartBtn: 'പട്ടികയിൽ ചേർത്തു',
        inCartLabel: 'പട്ടികയിൽ',
        repImageLabel: 'മാതൃകാ ചിത്രം (Representative)',
        myRequirement: 'എന്റെ ആവശ്യങ്ങൾ',
        sendRequirement: 'ആവശ്യങ്ങൾ അയക്കുക',
        continueAddingProducts: 'കൂടുതൽ പടക്കങ്ങൾ ചേർക്കുക',
        sendRequirementWhatsApp: 'വാട്ട്സ്ആപ്പിൽ ആവശ്യങ്ങൾ അയക്കുക',
        checkoutTitle: 'ഉപഭോക്തൃ വിവരങ്ങൾ',
        checkoutSubtitle: 'വാട്ട്സ്ആപ്പിൽ ആവശ്യങ്ങൾ അയക്കാൻ വിവരങ്ങൾ നൽകുക.',
        inStockLabel: 'ലഭ്യമാണ്',
        outOfStockLabel: 'ലഭ്യമല്ല',
        wholesalePriceTag: 'മൊത്തവില',
        contactForPrice: 'വിലയറിയാൻ വിളിക്കൂ',
        noProductsFound: 'പടക്കങ്ങൾ കണ്ടെത്താനായില്ല.',

        modalCategoryLabel: 'വിഭാഗം',
        modalPackSizeLabel: 'പാക്ക് അളവ്',
        modalPriceLabel: 'വില',
        modalDescriptionLabel: 'വിവരണം',
        modalSafetyTip: 'സുരക്ഷ: മുതിർന്നവരുടെ സാന്നിധ്യത്തിൽ തുറസ്സായ സ്ഥലത്ത് മാത്രം പൊട്ടിക്കുക.',
        modalAddToCartBtn: 'കാർട്ടിൽ ചേർക്കുക',
        modalOrderNowBtn: 'ഇപ്പോൾ ഓർഡർ ചെയ്യുക',
        modalWhatsAppEnquiryBtn: 'വാട്ട്സ്ആപ്പ് വിവരം',
        modalRequestDiscountBtn: 'ഡിസ്കൗണ്ട് അപേക്ഷ',
        modalCloseBtn: 'അടയ്ക്കുക',

        giftBoxSectionTitle: 'ഔദ്യോഗിക ഗിഫ്റ്റ് ബോക്സുകൾ',
        giftBoxSectionSubtitle: '16 മുതൽ 70 ഇനങ്ങൾ വരെയുള്ള 9 പ്രത്യേക ദീപാവലി ഗിഫ്റ്റ് ബോക്സുകൾ. കുടുംബങ്ങൾക്കും സമ്മാനങ്ങൾക്കും അനുയോജ്യം.',
        filterGiftAll: 'എല്ലാ ഗിഫ്റ്റ് ബോക്സുകളും (9)',
        filterGift16_30: '16–30 ഇനങ്ങൾ',
        filterGift35_50: '35–50 ഇനങ്ങൾ',
        filterGift60_70: '60–70 ഇനങ്ങൾ',
        viewContentsBtn: 'ഉള്ളടക്കം കാണുക',
        orderNowBtn: 'ഓർഡർ ചെയ്യുക',
        whatsInsideHeading: "ഇതിൽ എന്തൊക്കെയാണുള്ളത്?",
        tableColNo: 'നമ്പർ',
        tableColProduct: 'പടക്കത്തിന്റെ പേര്',
        tableColQty: 'അളവ്',
        boxContainsLabel: 'ഉള്ളടക്ക വിവരങ്ങൾ:',
        compareGiftBoxesTitle: '9 ഗിഫ്റ്റ് ബോക്സുകൾ താരതമ്യം ചെയ്യുക',
        compareGiftBoxesSubtitle: 'ഇനങ്ങളുടെ എണ്ണവും വിവരങ്ങളും എളുപ്പത്തിൽ താരതമ്യം ചെയ്യൂ.',

        priceListSectionTitle: 'വിലവിവരപ്പട്ടിക',
        priceListSectionSubtitle: 'പ്രണവ് ക്രാക്കേഴ്സ് – പടക്കങ്ങളും ഗിഫ്റ്റ് ബോക്സുകളും',
        priceListSearchPlaceholder: 'ഉൽപ്പന്നങ്ങൾ തിരയുക...',
        tableHeaderSNo: 'ക്രമ നമ്പർ',
        tableHeaderItemName: 'സാധനത്തിന്റെ പേര്',
        tableHeaderCompany: 'കമ്പനി',
        tableHeaderPrice: 'വില (₹)',
        printPriceSheetBtn: 'പ്രിന്റ് / സേവ് ചെയ്യുക',
        whatsappPriceListBtn: 'വാട്സാപ്പ് ചെയ്യുക',

        cartDrawerTitle: 'ഷോപ്പിംഗ് കാർട്ട്',
        cartEmptyMsg: 'നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്. പടക്കങ്ങൾ കണ്ട് "കാർട്ടിൽ ചേർക്കുക" ക്ലിക്ക് ചെയ്യുക.',
        cartSummaryLabel: 'ആകെ കണക്കാക്കിയ തുക:',
        cartTotalItems: 'ആകെ ഇനങ്ങൾ:',
        proceedCheckoutBtn: 'വിലാസം നൽകി ഓർഡർ ചെയ്യുക',
        orderWhatsAppBtn: 'വാട്ട്സ്ആപ്പിൽ ഓർഡർ അയക്കൂ',
        clearCartBtn: 'കാർട്ട് ഒഴിവാക്കുക',
        cartHelperText: 'പ്രണവ് ക്രാക്കേഴ്സ് ഓർഡർ സ്ഥിരീകരിച്ച ശേഷം മാത്രം പണം നൽകിയാൽ മതി.',

        checkoutTitle: 'ഡെലിവറി വിലാസ വിവരങ്ങൾ',
        checkoutSubtitle: 'ഓർഡർ ചെയ്യുന്നതിനായി നിങ്ങളുടെ പേരും വിലാസവും നൽകുക.',
        fieldName: 'പൂർണ്ണ പേര് *',
        fieldPhone: 'മൊബൈൽ നമ്പർ *',
        fieldAddress: 'ഡെലിവറി വിലാസം *',
        fieldCity: 'സ്ഥലം / നഗരം *',
        fieldState: 'സംസ്ഥാനം *',
        fieldPincode: 'പിൻ കോഡ് *',
        fieldNotes: 'പ്രത്യേക നിർദ്ദേശങ്ങൾ (ആവശ്യമെങ്കിൽ)',
        submitOrderBtn: 'ഓർഡർ സമർപ്പിക്കുക (Review Pending)',
        cancelBtn: 'റദ്ദാക്കുക',

        orderReceivedTitle: 'ഓർഡർ ലഭിച്ചു (ORDER RECEIVED)',
        orderReceivedMsg: 'നിങ്ങളുടെ ഓർഡർ ലഭിച്ചു. പ്രണവ് ക്രാക്കേഴ്സ് ടീം ഇത് പരിശോധിച്ച് വരികയാണ്.',
        orderNumberLabel: 'ഓർഡർ നമ്പർ:',
        orderStatusLabel: 'സ്റ്റാറ്റസ്:',
        statusUnderReview: 'പരിശോധനയിൽ (UNDER REVIEW)',
        orderReviewNotice: 'ഞങ്ങളുടെ ടീം ലഭ്യതയും അന്തിമ തുകയും സ്ഥിരീകരിക്കുന്നതാണ്.',
        chatWhatsAppOrderBtn: 'വാട്ട്സ്ആപ്പിൽ സംസാരിക്കാം',
        trackThisOrderBtn: 'ഓർഡർ സ്റ്റാറ്റസ് കാണുക',

        discountModalTitle: 'ബൾക്ക് ഡിസ്കൗണ്ട് അപേക്ഷ',
        discountModalSubtitle: 'നിങ്ങളുടെ മൊത്തവ്യാപാര ആവശ്യം സമർപ്പിക്കുക. മാനേജ്‌മെന്റ് പരിശോധിച്ച് അറിയിക്കും.',
        discountCustomerName: 'നിങ്ങളുടെ പേര് *',
        discountCustomerPhone: 'മൊബൈൽ നമ്പർ *',
        discountItemsLabel: 'ആവശ്യമായ പടക്കങ്ങൾ *',
        discountMessage: 'എണ്ണവും ബഡ്ജറ്റ് വിവരങ്ങളും *',
        sendDiscountRequestBtn: 'അപേക്ഷ അയക്കുക',

        trackOrderTitle: 'ഓർഡർ സ്റ്റാറ്റസ് അറിയാൻ',
        trackOrderSubtitle: 'ഓർഡർ നമ്പറോ ഫോൺ നമ്പറോ നൽകി നിലവിലെ സ്ഥിതി അറിയുക.',
        trackInputPlaceholder: 'ഓർഡർ നമ്പർ അല്ലെങ്കിൽ ഫോൺ നമ്പർ നൽകുക...',
        trackLookupBtn: 'സ്റ്റാറ്റസ് പരിശോധിക്കുക',
        payNowBtn: 'പണം നൽകുക',
        confirmPaymentBtn: 'പണം നൽകിയെന്ന് സ്ഥിരീകരിക്കുക',

        howToOrderTitle: 'എങ്ങനെ ഓർഡർ ചെയ്യാം? (3 എളുപ്പവഴികൾ)',
        howToOrderSubtitle: 'എല്ലാവർക്കും എളുപ്പത്തിൽ മനസ്സിലാക്കാവുന്ന ഓർഡർ രീതി',
        step1Title: 'തിരഞ്ഞെടുക്കുക',
        step1Desc: 'കാറ്റലോഗിൽ നിന്നോ ഗിഫ്റ്റ് ബോക്സുകളിൽ നിന്നോ ആവശ്യമായവ കാർട്ടിൽ ചേർക്കുക.',
        step2Title: 'വിലാസം നൽകുക',
        step2Desc: 'ഡെലിവറി വിലാസം നൽകി ഓർഡർ സമർപ്പിക്കുക.',
        step3Title: 'സ്ഥിരീകരണവും പേയ്‌മെന്റും',
        step3Desc: 'ഞങ്ങളുടെ ടീം സ്ഥിരീകരിച്ച ശേഷം സുരക്ഷിതമായി പണം നൽകാം.',

        aboutSectionTitle: 'പ്രണവ് ക്രാക്കേഴ്സിനെക്കുറിച്ച്',
        aboutDesc: 'ശിവകാശിയിൽ നിന്നുള്ള ഏറ്റവും മികച്ച പടക്കങ്ങൾ മിതമായ മൊത്തവിലയിൽ പ്രണവ് ക്രാക്കേഴ്സ് നൽകുന്നു.',
        value1Title: 'ഗുണനിലവാരം (Quality)',
        value1Desc: 'ശിവകാശിയിലെ മികച്ച നിർമ്മാതാക്കളിൽ നിന്നുള്ള പടക്കങ്ങൾ.',
        value2Title: 'വിശ്വാസ്യത (Trust)',
        value2Desc: 'കൃത്യമായ ആശയവിനിമയവും യഥാർത്ഥ മൊത്തവിലയും.',
        value3Title: 'ഉപഭോക്തൃ സംതൃപ്തി',
        value3Desc: 'നിങ്ങളുടെ ഓരോ ആഘോഷവും മനോഹരമാക്കുകയാണ് ഞങ്ങളുടെ ലക്ഷ്യം.',

        safetySectionTitle: 'സുരക്ഷാ നിർദ്ദേശങ്ങൾ',
        safetySectionSubtitle: 'സുരക്ഷിതവും സന്തോഷകരവുമായ ദീപാവലിക്ക്',
        safety1: 'ഓരോ പെട്ടിയിലും നൽകിയിരിക്കുന്ന നിർദ്ദേശങ്ങൾ വായിക്കുക.',
        safety2: 'പടക്കങ്ങൾ എപ്പോഴും തുറസ്സായ സ്ഥലത്ത് മാത്രം പൊട്ടിക്കുക.',
        safety3: 'കുട്ടികൾ മുതിർന്നവരുടെ സാന്നിധ്യത്തിൽ മാത്രം പൊട്ടിക്കുക.',
        safety4: 'സമീപത്ത് ഒരു ബക്കറ്റ് വെള്ളമോ മണലോ കരുതുക.',
        safety5: 'എല്ലാ സുരക്ഷാ നിയമങ്ങളും പാലിക്കുക.',

        contactSectionTitle: 'പ്രണവ് ക്രാക്കേഴ്സ് ബന്ധപ്പെടുക',
        contactSectionSubtitle: 'നിങ്ങളുടെ പടക്ക ആവശ്യങ്ങൾക്കും മൊത്ത ഓർഡറുകൾക്കും ബന്ധപ്പെടുക',
        contactLocationLabel: 'വിൽപ്പന കേന്ദ്രം',
        contactLocationVal: 'ശിവകാശി, തമിഴ്നാട്, ഇന്ത്യ',
        contactPhoneLabel: 'ഫോൺ & വാട്ട്സ്ആപ്പ് നമ്പറുകൾ',
        callNowBtn: 'വിളിക്കുക',

        footerTagline: 'പ്രീമിയം പടക്കങ്ങൾ • മൊത്തവ്യാപാരം',
        footerQuickLinksTitle: 'പ്രധാന ലിങ്കുകൾ',
        footerContactTitle: 'ബന്ധപ്പെടുക',
        footerLegalNote: 'കുറിപ്പ്: വിൽപ്പനയും വിതരണവും നിയമാനുസൃത നിബന്ധനകൾക്ക് വിധേയമാണ്.',
        footerCopyright: '© 2026 പ്രണവ് ക്രാക്കേഴ്സ്, ശിവകാശി. എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.',

        toastAdded: 'കാർട്ടിൽ ചേർത്തു',
        toastRemoved: 'കാർട്ടിൽ നിന്ന് ഒഴിവാക്കി',
        toastCleared: 'കാർട്ട് ഒഴിവാക്കി',
        toastOrderPlaced: 'ഓർഡർ സമർപ്പിച്ചു! സ്റ്റാറ്റസ്: പരിശോധനയിൽ',
        toastDiscountSent: 'ഡിസ്കൗണ്ട് അപേക്ഷ അയച്ചു'
    },

    kn: {
        navHome: 'ಮುಖಪುಟ',
        navProducts: 'ಪಟಾಕಿಗಳು',
        navGiftBoxes: 'ಗಿಫ್ಟ್ ಬಾಕ್ಸ್',
        navPriceList: 'ಬೆಲೆ ಪಟ್ಟಿ',
        navHowToOrder: 'ಆರ್ಡರ್ ವಿಧಾನ',
        navAbout: 'ನಮ್ಮ ಬಗ್ಗೆ',
        navContact: 'ಸಂಪರ್ಕಿಸಿ',
        navCart: 'ನನ್ನ ಅಗತ್ಯಗಳ ಪಟ್ಟಿ',
        navTrackOrder: 'ಟ್ರ್ಯಾಕ್',
        headerWhatsAppBtn: 'ವಾಟ್ಸಾಪ್',

        heroTagline: 'ಪ್ರಣವ್ ಕ್ರ್ಯಾಕರ್ಸ್ ಜೊತೆ ನಿಮ್ಮ ಹಬ್ಬವನ್ನು ಇನ್ನಷ್ಟು ಪ್ರಕಾಶಮಾನವಾಗಿಸಿ',
        heroSubtitle: 'ನೇರವಾಗಿ ಶಿವಕಾಶಿ ಪಟಾಕಿಗಳು ಮತ್ತು ಗಿಫ್ಟ್ ಬಾಕ್ಸ್‌ಗಳು',
        heroLocation: 'ಶಿವಕಾಶಿ, ತಮಿಳುನಾಡು',
        heroPrimaryCta: 'ಪಟಾಕಿಗಳನ್ನು ನೋಡಿ',
        heroSecondaryCta: 'ಗಿಫ್ಟ್ ಬಾಕ್ಸ್‌ಗಳು',
        heroWhatsAppCta: 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಸಂಪರ್ಕಿಸಿ',

        qaTitle: 'ತ್ವರಿತ ಸೇವೆಗಳು',
        qaProductsTitle: 'ಪಟಾಕಿಗಳು',
        qaProductsDesc: 'ಎಲ್ಲಾ ರೀತಿಯ ಪಟಾಕಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
        qaGiftBoxesTitle: 'ಗಿಫ್ಟ್ ಬಾಕ್ಸ್‌ಗಳು',
        qaGiftBoxesDesc: '5 ಎಕೋ ಸಿಟಿ ಗಿಫ್ಟ್ ಬಾಕ್ಸ್‌ಗಳು',
        qaPriceListTitle: 'ಬೆಲೆ ಪಟ್ಟಿ',
        qaPriceListDesc: 'ಸಗಟು ಬೆಲೆ ವಿವರಗಳನ್ನು ನೋಡಿ',
        qaOrderTitle: 'ನನ್ನ ಅಗತ್ಯಗಳ ಪಟ್ಟಿ',
        qaOrderDesc: 'ಆಯ್ಕೆ ಮಾಡಿದ ವಸ್ತುಗಳನ್ನು ಕಳುಹಿಸಿ',

        catSectionTitle: 'ಪಟಾಕಿ ವಿಭಾಗಗಳು',
        catSectionSubtitle: 'ಶಿವಕಾಶಿಯ ಉತ್ತಮ ಗುಣമಟ್ಟದ ಪಟಾಕಿಗಳಿಂದ ಆಯ್ಕೆ ಮಾಡಿ',
        viewProductsBtn: 'ಉತ್ಪನ್ನಗಳನ್ನು ನೋಡಿ',

        catalogSectionTitle: 'ನಮ್ಮ ಪಟಾಕಿ ಕ್ಯಾಟಲಾಗ್',
        catalogSearchHeading: 'ನೀವು ಏನು ಹುಡುಕುತ್ತಿದ್ದೀರಿ?',
        catalogSearchPlaceholder: 'ಪಟಾಕಿಗಳನ್ನು ಹುಡುಕಿ (ಸುರುಸುರು ಬತ್ತಿ, ಹೂಕುಂಡ, ರಾಕೆಟ್)...',
        filterAll: 'ಎಲ್ಲಾ ಪಟಾಕಿಗಳು',
        viewDetailsBtn: 'ಪೂರ್ಣ ವಿವರ',
        addToCartBtn: 'ಪಟ್ಟಿಗೆ ಸೇರಿಸಿ',
        addedToCartBtn: 'ಪಟ್ಟಿಯಲ್ಲಿದೆ',
        inCartLabel: 'ಪಟ್ಟಿಯಲ್ಲಿ',
        repImageLabel: 'ಮಾದರಿ ಚಿತ್ರ (Representative)',
        myRequirement: 'ನನ್ನ ಅಗತ್ಯಗಳ ಪಟ್ಟಿ',
        sendRequirement: 'ಅಗತ್ಯಗಳ ಪಟ್ಟಿ ಕಳುಹಿಸಿ',
        continueAddingProducts: 'ಇನ್ನಷ್ಟು ಪಟಾಕಿಗಳನ್ನು ಸೇರಿಸಿ',
        sendRequirementWhatsApp: 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಕಳುಹಿಸಿ',
        checkoutTitle: 'ಗ್ರಾಹಕರ ವಿವರಗಳು',
        checkoutSubtitle: 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಕಳುಹಿಸಲು ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.',
        inStockLabel: 'ಲಭ್ಯವಿದೆ',
        outOfStockLabel: 'ಪ್ರಸ್ತುತ ಲಭ್ಯವಿಲ್ಲ',
        wholesalePriceTag: 'ಸಗಟು ಬೆಲೆ',
        contactForPrice: 'ಬೆಲೆಗಾಗಿ ಸಂಪರ್ಕಿಸಿ',
        noProductsFound: 'ಯಾವುದೇ ಪಟಾಕಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',

        modalCategoryLabel: 'ವರ್ಗ',
        modalPackSizeLabel: 'ಪ್ಯಾಕ್ ಗಾತ್ರ',
        modalPriceLabel: 'ಬೆಲೆ',
        modalDescriptionLabel: 'ವಿವರಣೆ',
        modalSafetyTip: 'ಸುರಕ್ಷತೆ: ಹಿರಿಯರ ಸಮ್ಮುಖದಲ್ಲಿ ತೆರೆದ ಜಾಗದಲ್ಲಿ ಮಾತ್ರ ಸಿಡಿಸಿ.',
        modalAddToCartBtn: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
        modalOrderNowBtn: 'ಈಗಲೇ ಆರ್ಡರ್ ಮಾಡಿ',
        modalWhatsAppEnquiryBtn: 'ವಾಟ್ಸಾಪ್ ವಿಚಾರಣೆ',
        modalRequestDiscountBtn: 'ರಿಯಾಯಿತಿ ವಿನಂತಿ',
        modalCloseBtn: 'ಮುಚ್ಚಿ',

        giftBoxSectionTitle: 'ಅಧಿಕೃತ ಗಿಫ್ಟ್ ಬಾಕ್ಸ್‌ಗಳು',
        giftBoxSectionSubtitle: '16 ರಿಂದ 70 ರವರೆಗಿನ 9 ವಿಶೇಷ ಗಿಫ್ಟ್ ಬಾಕ್ಸ್‌ಗಳು. ಕುಟುಂಬ ಮತ್ತು ಉಡುಗೊರೆಗಳಿಗೆ ಅತ್ಯುತ್ತಮ.',
        filterGiftAll: 'ಎಲ್ಲಾ ಗಿಫ್ಟ್ ಬಾಕ್ಸ್‌ಗಳು (9)',
        filterGift16_30: '16–30 ವಸ್ತುಗಳು',
        filterGift35_50: '35–50 ವಸ್ತುಗಳು',
        filterGift60_70: '60–70 ವಸ್ತುಗಳು',
        viewContentsBtn: 'ವಿವರಗಳನ್ನು ನೋಡಿ',
        orderNowBtn: 'ಆರ್ಡರ್ ಮಾಡಿ',
        whatsInsideHeading: "ಇದರಲ್ಲಿ ಏನೆಲ್ಲಾ ಇದೆ?",
        tableColNo: 'ಸಂಖ್ಯೆ',
        tableColProduct: 'ಪಟಾಕಿಯ ಹೆಸರು',
        tableColQty: 'ಪ್ರಮಾಣ',
        boxContainsLabel: 'ಒಳಗೊಂಡಿರುವ ವಸ್ತುಗಳ ವಿವರ:',
        compareGiftBoxesTitle: '9 ಗಿಫ್ಟ್ ಬಾಕ್ಸ್‌ಗಳನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ',
        compareGiftBoxesSubtitle: 'ವಸ್ತುಗಳ ಸಂಖ್ಯೆ ಮತ್ತು ವಿವರಗಳನ್ನು ಸುಲಭವಾಗಿ ಹೋಲಿಸಿ.',

        priceListSectionTitle: 'ಬೆಲೆ ಪಟ್ಟಿ',
        priceListSectionSubtitle: 'ಪ್ರಣವ್ ಕ್ರ್ಯಾಕರ್ಸ್ – ಪಟಾಕಿಗಳು & ಗಿಫ್ಟ್ ಬಾಕ್ಸ್‌ಗಳು',
        priceListSearchPlaceholder: 'ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...',
        tableHeaderSNo: 'ಕ್ರಮ ಸಂಖ್ಯೆ',
        tableHeaderItemName: 'ವಸ್ತುವಿನ ಹೆಸರು',
        tableHeaderCompany: 'ಕಂಪನಿ',
        tableHeaderPrice: 'ಬೆಲೆ (₹)',
        printPriceSheetBtn: 'ಮುದ್ರಿಸಿ / ಬೆಲೆ ಪಟ್ಟಿ ಉಳಿಸಿ',
        whatsappPriceListBtn: 'ವಾಟ್ಸಾಪ್ ಮಾಡಿ',

        cartDrawerTitle: 'ಶಾಪಿಂಗ್ ಕಾರ್ಟ್',
        cartEmptyMsg: 'ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ. "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ" ಕ್ಲಿಕ್ ಮಾಡಿ.',
        cartSummaryLabel: 'ಅಂದಾಜು ಒಟ್ಟು ಮೊತ್ತ:',
        cartTotalItems: 'ಒಟ್ಟು ವಸ್ತುಗಳು:',
        proceedCheckoutBtn: 'ವಿಳಾಸ ನೀಡಿ ಆರ್ಡರ್ ಮಾಡಿ',
        orderWhatsAppBtn: 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಆರ್ಡರ್ ಕಳುಹಿಸಿ',
        clearCartBtn: 'ಕಾರ್ಟ್ ಖಾಲಿ ಮಾಡಿ',
        cartHelperText: 'ಪ್ರಣವ್ ಕ್ರ್ಯಾಕರ್ಸ್ ಪರಿಶೀಲಿಸಿದ ನಂತರವೇ ಪಾವತಿ ಮಾಡಬೇಕು.',

        checkoutTitle: 'ವಿತರಣೆ ಮತ್ತು ಸಂಪರ್ಕ ವಿವರಗಳು',
        checkoutSubtitle: 'ಆರ್ಡರ್ ಮಾಡಲು ನಿಮ್ಮ ಹೆಸರು, ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಮತ್ತು ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ.',
        fieldName: 'ಪೂರ್ಣ ಹೆಸರು *',
        fieldPhone: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ *',
        fieldAddress: 'ವಿತರಣಾ ವಿಳಾಸ *',
        fieldCity: 'ಊರು / ನಗರ *',
        fieldState: 'ರಾಜ್ಯ *',
        fieldPincode: 'ಪಿನ್ ಕೋಡ್ *',
        fieldNotes: 'ವಿಶೇಷ ಸೂಚನೆಗಳು (ಐಚ್ಛಿಕ)',
        submitOrderBtn: 'ಆರ್ಡರ್ ಸಲ್ಲಿಸಿ (Review Pending)',
        cancelBtn: 'ರದ್ದುಮಾಡಿ',

        orderReceivedTitle: 'ಆರ್ಡರ್ ಸ್ವೀಕರಿಸಲಾಗಿದೆ (ORDER RECEIVED)',
        orderReceivedMsg: 'ನಿಮ್ಮ ಆರ್ಡರ್ ಸ್ವೀಕರಿಸಲಾಗಿದೆ ಮತ್ತು ಪ್ರಣವ್ ಕ್ರ್ಯಾಕರ್ಸ್ ತಂಡ ಪರಿಶೀಲಿಸುತ್ತಿದೆ.',
        orderNumberLabel: 'ಆರ್ಡರ್ ಸಂಖ್ಯೆ:',
        orderStatusLabel: 'ಸ್ಥಿತಿ:',
        statusUnderReview: 'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ (UNDER REVIEW)',
        orderReviewNotice: 'ನಮ್ಮ ತಂಡ ಲಭ್ಯತೆ ಮತ್ತು ಅಂತಿಮ ಬೆಲೆಯನ್ನು ದೃಢಪಡಿಸುತ್ತದೆ.',
        chatWhatsAppOrderBtn: 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಮಾತನಾಡಿ',
        trackThisOrderBtn: 'ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',

        discountModalTitle: 'ವಿಶೇಷ ಸಗಟು ರಿಯಾಯಿತಿ ವಿನಂತಿ',
        discountModalSubtitle: 'ನಿಮ್ಮ ಸಗಟು ಅಗತ್ಯವನ್ನು ಸಲ್ಲಿಸಿ. ನಮ್ಮ ತಂಡ ಪರಿಶೀಲಿಸಿ ತಿಳಿಸುತ್ತದೆ.',
        discountCustomerName: 'ನಿಮ್ಮ ಹೆಸರು *',
        discountCustomerPhone: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ *',
        discountItemsLabel: 'ಆಯ್ಕೆ ಮಾಡಿದ ಪಟಾಕಿಗಳು *',
        discountMessage: 'ಪ್ರಮಾಣ ಮತ್ತು ಬಜೆಟ್ ವಿವರಗಳು *',
        sendDiscountRequestBtn: 'ವಿನಂತಿ ಕಳುಹಿಸಿ',

        trackOrderTitle: 'ಆರ್ಡರ್ ಸ್ಥಿತಿ ತಿಳಿಯಿರಿ',
        trackOrderSubtitle: 'ನಿಮ್ಮ ಆರ್ಡರ್ ಸಂಖ್ಯೆ ಅಥವಾ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನೀಡಿ ಪ್ರಸ್ತುತ ಸ್ಥಿತಿಯನ್ನು ತಿಳಿಯಿರಿ.',
        trackInputPlaceholder: 'ಆರ್ಡರ್ ಸಂಖ್ಯೆ ಅಥವಾ ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ...',
        trackLookupBtn: 'ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ',
        payNowBtn: 'ಪಾವತಿ ಮಾಡಿ',
        confirmPaymentBtn: 'ಪಾವತಿ ದೃಢೀಕರಿಸಿ',

        howToOrderTitle: 'ಆರ್ಡರ್ ಮಾಡುವುದು ಹೇಗೆ? (3 ಸುಲಭ ಹಂತಗಳು)',
        howToOrderSubtitle: 'ಎಲ್ಲರಿಗೂ ಸುಲಭವಾಗಿ ಅರ್ಥವಾಗುವ ಸರಳ ಆರ್ಡರ್ ವಿಧಾನ',
        step1Title: 'ಆಯ್ಕೆ ಮಾಡಿ',
        step1Desc: 'ಕ್ಯಾಟಲಾಗ್ ಅಥವಾ ಗಿಫ್ಟ್ ಬಾಕ್ಸ್‌ಗಳಿಂದ ಬೇಕಾದ ಪಟಾಕಿಗಳನ್ನು ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ.',
        step2Title: 'ವಿಳಾಸ ನಮೂದಿಸಿ',
        step2Desc: 'ವಿತರಣಾ ವಿಳಾಸ ನೀಡಿ ಆರ್ಡರ್ ಸಲ್ಲಿಸಿ.',
        step3Title: 'ದೃಢೀಕರಣ ಮತ್ತು ಪಾವತಿ',
        step3Desc: 'ನಮ್ಮ ತಂಡ ದೃಢಪಡಿಸಿದ ನಂತರ ಸುರಕ್ಷಿತವಾಗಿ ಪಾವತಿ ಮಾಡಿ.',

        aboutSectionTitle: 'ಪ್ರಣವ್ ಕ್ರ್ಯಾಕರ್ಸ್ ಬಗ್ಗೆ',
        aboutDesc: 'ಪ್ರಣವ್ ಕ್ರ್ಯಾಕರ್ಸ್ ಶಿವಕಾಶಿಯಿಂದ ನೇರವಾಗಿ ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಪಟಾಕಿಗಳನ್ನು ನ್ಯಾಯಯುತ ಸಗಟು ಬೆಲೆಯಲ್ಲಿ ನೀಡುತ್ತದೆ.',
        value1Title: 'ಗುಣಮಟ್ಟ (Quality)',
        value1Desc: 'ಶಿವಕಾಶಿಯ ಪ್ರಮುಖ ತಯಾರಕರಿಂದ ಆಯ್ಕೆ ಮಾಡಿದ ಪಟಾಕಿಗಳು.',
        value2Title: 'ವಿಶ್ವಾಸಾರ್ಹತೆ (Trust)',
        value2Desc: 'ಸ್ಪಷ್ಟ ಸಂವಹನ ಮತ್ತು ಪ್ರಾಮಾಣಿಕ ಸಗಟು ಬೆಲೆಗಳು.',
        value3Title: 'ಗ್ರಾಹಕರ ತೃಪ್ತಿ',
        value3Desc: 'ನಿಮ್ಮ ಪ್ರತಿಯೊಂದು ಹಬ್ಬವನ್ನು ಸಂಭ್ರಮವಾಗಿಸುವುದೇ ನಮ್ಮ ಗುರಿ.',

        safetySectionTitle: 'ಸುರಕ್ಷತಾ ಮಾರ್ಗಸೂಚಿಗಳು',
        safetySectionSubtitle: 'ಸುರಕ್ಷಿತ ಮತ್ತು ಸಂತೋಷದಾಯಕ ದೀಪಾವಳಿಗಾಗಿ',
        safety1: 'ಪ್ರತಿ ಪ್ಯಾಕೆಟ್‌ನಲ್ಲಿ ಮುದ್ರಿಸಲಾದ ಸೂಚನೆಗಳನ್ನು ಓದಿ.',
        safety2: 'ಪಟಾಕಿಗಳನ್ನು ಯಾವಾಗಲೂ ತೆರೆದ ಜಾಗದಲ್ಲಿ ಮಾತ್ರ ಸಿಡಿಸಿ.',
        safety3: 'ಮಕ್ಕಳು ಯಾವಾಗಲೂ ಹಿರಿಯರ ಉಪಸ್ಥಿತಿಯಲ್ಲಿ ಮಾತ್ರ ಸಿಡಿಸಬೇಕು.',
        safety4: 'ಬಳಿ ನೀರಿನ ಅಥವಾ ಮರಳಿನ ಬಕೆಟ್ ಸಿದ್ಧವಾಗಿಡಿ.',
        safety5: 'ಎಲ್ಲಾ ಸುರಕ್ಷತಾ ನಿಯಮಗಳನ್ನು ಪಾಲಿಸಿ.',

        contactSectionTitle: 'ಪ್ರಣವ್ ಕ್ರ್ಯಾಕರ್ಸ್ ಸಂಪರ್ಕಿಸಿ',
        contactSectionSubtitle: 'ಸಗಟು ಆರ್ಡರ್ ಮತ್ತು ವಿಚಾರಣೆಗಳಿಗಾಗಿ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
        contactLocationLabel: 'ಮಾರಾಟ ಕೇಂದ್ರ',
        contactLocationVal: 'ಶಿವಕಾಶಿ, ತಮಿಳುನಾಡು, ಭಾರತ',
        contactPhoneLabel: 'ಫೋನ್ ಮತ್ತು ವಾಟ್ಸಾಪ್ ಸಂಖ್ಯೆಗಳು',
        callNowBtn: 'ಕರೆ ಮಾಡಿ',

        footerTagline: 'ಪ್ರೀಮಿಯಂ ಪಟಾಕಿಗಳು • ಸಗಟು ಮಾರಾಟ',
        footerQuickLinksTitle: 'ಮುಖ್ಯ ಲಿಂಕ್‌ಗಳು',
        footerContactTitle: 'ಸಂಪರ್ಕಿಸಿ',
        footerLegalNote: 'ಸೂಚನೆ: ಪಟಾಕಿ ಮಾರಾಟ ಮತ್ತು ಸಾಗಾಣಿಕೆ ಕಾನೂನು ನಿಯಮಗಳಿಗೆ ಒಳಪಟ್ಟಿರುತ್ತದೆ.',
        footerCopyright: '© 2026 ಪ್ರಣವ್ ಕ್ರ್ಯಾಕರ್ಸ್, ಶಿವಕಾಶಿ. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',

        toastAdded: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ',
        toastRemoved: 'ಕಾರ್ಟ್‌ನಿಂದ ತೆಗೆದುಹಾಕಲಾಗಿದೆ',
        toastCleared: 'ಕಾರ್ಟ್ ಖಾಲಿ ಮಾಡಲಾಗಿದೆ',
        toastOrderPlaced: 'ಆರ್ಡರ್ ಸಲ್ಲಿಸಲಾಗಿದೆ! ಸ್ಥಿತಿ: ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
        toastDiscountSent: 'ರಿಯಾಯಿತಿ ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ'
    }
};

class LanguageManager {
    static getSupportedLanguages() {
        return SUPPORTED_LANGUAGES;
    }

    static getLanguage() {
        const stored = localStorage.getItem(STORAGE_KEYS.LANGUAGE) || 'en';
        return TRANSLATIONS[stored] ? stored : 'en';
    }

    static setLanguage(lang) {
        if (!TRANSLATIONS[lang]) lang = 'en';
        localStorage.setItem(STORAGE_KEYS.LANGUAGE, lang);
        document.documentElement.lang = lang;
        this.applyTranslations();
        this.updateLanguageUI();
        window.dispatchEvent(new CustomEvent('languageChanged', { detail: { lang } }));
    }

    static t(key) {
        const lang = this.getLanguage();
        return (TRANSLATIONS[lang] && TRANSLATIONS[lang][key]) || (TRANSLATIONS['en'] && TRANSLATIONS['en'][key]) || key;
    }

    static updateLanguageUI() {
        const currentLang = this.getLanguage();
        
        // Update Desktop and Mobile dropdowns/selectors
        document.querySelectorAll('.lang-select-dropdown').forEach(sel => {
            sel.value = currentLang;
        });

        // Update mobile language grid buttons
        document.querySelectorAll('.mobile-lang-btn, .lang-menu-item').forEach(btn => {
            const btnLang = btn.getAttribute('data-lang');
            btn.classList.toggle('active', btnLang === currentLang);
        });

        // Update current language label display
        const langObj = SUPPORTED_LANGUAGES.find(l => l.code === currentLang) || SUPPORTED_LANGUAGES[0];
        document.querySelectorAll('.current-lang-name').forEach(el => {
            el.textContent = langObj.nativeName;
        });
    }

    static applyTranslations() {
        const lang = this.getLanguage();
        const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;

        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (dict[key]) {
                el.innerHTML = dict[key];
            }
        });

        document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
            const key = el.getAttribute('data-i18n-placeholder');
            if (dict[key]) {
                el.setAttribute('placeholder', dict[key]);
            }
        });

        document.querySelectorAll('[data-i18n-title]').forEach(el => {
            const key = el.getAttribute('data-i18n-title');
            if (dict[key]) {
                el.setAttribute('title', dict[key]);
                el.setAttribute('aria-label', dict[key]);
            }
        });
    }
}
