/**
 * =============================================================================
 * PRANAV CRACKERS - MULTILINGUAL LOCALIZATION & TRANSLATIONS
 * =============================================================================
 * 
 * HOW TO USE THIS FILE:
 * - Supported Languages: English (en), Tamil (ta), Hindi (hi), Telugu (te),
 *   Malayalam (ml), Kannada (kn), Gujarati (gu), Marathi (mr), Bengali (bn).
 * - TO EDIT ANY BUTTON, LABEL OR BANNER TEXT:
 *   Find the language code below (e.g., 'en' for English, 'ta' for Tamil)
 *   and edit the corresponding text value.
 * =============================================================================
 */

const SUPPORTED_LANGUAGES = [
    { code: 'en', label: 'English', nativeName: 'English' },
    { code: 'ta', label: 'Tamil', nativeName: 'தமிழ்' },
    { code: 'hi', label: 'Hindi', nativeName: 'हिन्दी' },
    { code: 'te', label: 'Telugu', nativeName: 'తెలుగు' },
    { code: 'ml', label: 'Malayalam', nativeName: 'മലയാളം' },
    { code: 'kn', label: 'Kannada', nativeName: 'ಕನ್ನಡ' },
    { code: 'gu', label: 'Gujarati', nativeName: 'ગુજરાતી' },
    { code: 'mr', label: 'Marathi', nativeName: 'मराठी' },
    { code: 'bn', label: 'Bengali', nativeName: 'বাংলা' }
];

const TRANSLATIONS = {
    en: {
        announcementBadge: '💥 DIWALI 2026',
        announcementText: 'Direct Sivakasi Factory Wholesale • Up to 70% Off Retail MRP • Safe All-India Delivery',
        announcementPhone: '📞 Sivakasi Desk: +91 77085 32334',
        brandSub: 'Direct Sivakasi Wholesale Fireworks',
        btnWhatsApp: 'WhatsApp',
        btnCall: 'Call Us',
        btnQuotation: 'Quotation',
        trustDirectFactory: 'Direct Sivakasi Factory',
        trustDirectFactorySub: 'No middlemen markups',
        trustGreen: 'CSIR-NEERI Green',
        trustGreenSub: 'Certified eco-friendly',
        trustBrands: 'Genuine Brands',
        trustBrandsSub: '100% Genuine Sivakasi',
        trustTransport: 'Safe Transport',
        trustTransportSub: 'Direct delivery across India',
        diwaliSaleLive: '🔥 DIWALI 2026 FACTORY SALE LIVE',
        diwaliHeroTitle: 'Sivakasi Direct Crackers at Factory Wholesale Rates',
        diwaliHeroDesc: 'Select your crackers below, see instant live estimated savings, and send your complete requirement on WhatsApp in 30 seconds.',
        statVarieties: 'Varieties',
        statFactoryOff: 'Factory Off',
        statMinLimit: 'Min. Limit',
        searchPlaceholder: 'Search 94+ crackers (e.g. Flower Pot, Chakkar, 12 Shot, Gift Box)...',
        viewCards: 'Cards',
        viewRateSheet: 'Rate Sheet',
        catAll: 'All Crackers',
        catFlowerPots: 'Flower Pots',
        catGroundChakkars: 'Ground Chakkars',
        catSoundCrackers: 'Sound Crackers',
        catBombs: 'Bombs',
        catRockets: 'Rockets',
        catSkyShots: 'Sky Shots',
        catSparklers: 'Sparklers',
        catFancyItems: 'Fancy Items',
        catGarlands: 'Garlands / Lar',
        catGiftBoxes: 'Gift Boxes',
        saveDiscount: 'SAVE 60%',
        subtotalText: 'Subtotal',
        mrpText: 'Retail MRP',
        wholesaleRateText: 'Wholesale Rate',
        quantityText: 'Quantity',
        itemsText: 'Items',
        itemText: 'Item',
        wholesaleTotalText: 'Wholesale Total:',
        saveText: 'Save',
        viewQuotationBtn: 'VIEW QUOTATION & WHATSAPP',
        sivakasiSuper: 'PRANAV CRACKERS • SIVAKASI',
        estQuotationHeading: 'ESTIMATED QUOTATION',
        selectedCrackers: 'SELECTED CRACKERS',
        clearAllBtn: 'Clear All',
        totalSelected: 'Total Selected Items:',
        estRetailMrp: 'Estimated Retail MRP:',
        estWholesaleTotal: 'ESTIMATED WHOLESALE TOTAL:',
        customerDetailsHeader: 'CUSTOMER & DELIVERY DETAILS',
        labelName: 'Full Name *',
        labelPhone: 'WhatsApp / Mobile Number *',
        labelAddress: 'Delivery Address *',
        labelCity: 'City / Town *',
        labelState: 'State *',
        labelPincode: 'PIN Code *',
        labelNotes: 'Delivery Notes (Optional)',
        placeholderName: 'Enter your full name',
        placeholderPhone: '10-digit mobile number',
        placeholderAddress: 'House / Flat No., Street, Area',
        placeholderCity: 'City',
        placeholderState: 'Tamil Nadu',
        placeholderPincode: '6-digit PIN Code',
        placeholderNotes: 'e.g. Preferred transport service, delivery timing',
        legalDisclaimer: '⚠️ Legal Notice: In strict compliance with Supreme Court of India directives and CSIR-NEERI green fireworks guidelines, this platform functions as a digital price estimation tool. Products are supplied directly from licensed Sivakasi manufacturers.',
        btnSendWhatsapp: 'SEND REQUIREMENT ON WHATSAPP',
        reqPreparedTitle: 'Requirement Prepared!',
        reqPreparedRef: 'Quotation Reference:',
        reqPreparedMsg: 'Your estimated quotation has been prepared and opened in WhatsApp. Please press Send inside WhatsApp to confirm your requirement with our Sivakasi desk.',
        continueBrowsing: 'Continue Browsing',
        trackTitle: 'Track Quotation / Requirement',
        trackPlaceholder: 'Enter Quotation ID (e.g. PCQ-260915-1042) or Phone',
        trackBtn: 'Track',
        footerDesk: 'WhatsApp Sivakasi Desk',
        footerCall: 'Call +91 77085 32334',
        footerTrack: 'Track Quotation',
        footerAdmin: 'Admin Login',
        footerCopyright: '© 2026 PRANAV CRACKERS, Sivakasi. All Rights Reserved. Compliant with CSIR-NEERI Green Fireworks Guidelines.',
        emptySearchTitle: 'No crackers found matching',
        emptySearchDesc: 'Try searching for popular crackers like Flower Pot, Chakkar, 12 Shot, Sparklers, or Gift Box.',
        clearSearchBtn: 'Clear Search',
        showAllBtn: 'Show All Crackers'
    },

    ta: {
        announcementBadge: '💥 தீபாவளி 2026',
        announcementText: 'சிவகாசி நேரடி தொழிற்சாலை மொத்த விலை • 70% வரை தள்ளுபடி • இந்தியா முழுவதும் நேரடி டெலிவரி',
        announcementPhone: '📞 சிவகாசி மையம்: +91 77085 32334',
        brandSub: 'சிவகாசி நேரடி மொத்த பட்டாசுகள்',
        btnWhatsApp: 'வாட்ஸ்அப்',
        btnCall: 'அழைக்க',
        btnQuotation: 'விலைப்பட்டியல்',
        trustDirectFactory: 'சிவகாசி நேரடி தொழிற்சாலை',
        trustDirectFactorySub: 'இடைத்தரகர் கமிஷன் இல்லை',
        trustGreen: 'CSIR-NEERI பசுமை பட்டாசு',
        trustGreenSub: 'அங்கீகரிக்கப்பட்ட சுற்றுச்சூழல் பாதுகாப்பு',
        trustBrands: 'அசல் பிராண்டுகள்',
        trustBrandsSub: '100% Genuine Sivakasi',
        trustTransport: 'பாதுகாப்பான போக்குவரத்து',
        trustTransportSub: 'இந்தியா முழுவதும் நேரடி டெலிவரி',
        diwaliSaleLive: '🔥 தீபாவளி 2026 நேரடி விற்பனை ஆரம்பம்',
        diwaliHeroTitle: 'சிவகாசி நேரடி பட்டாசுகள் தொழிற்சாலை மொத்த விலையில்',
        diwaliHeroDesc: 'பட்டாசுகளைத் தேர்ந்தெடுத்து, நேரடி தள்ளுபடி மதிப்பைக் கண்டு, 30 வினாடிகளில் வாட்ஸ்அப்பில் உங்கள் தேவையை அனுப்பவும்.',
        statVarieties: 'வகைகள்',
        statFactoryOff: 'நேரடி தள்ளுபடி',
        statMinLimit: 'குறைந்தபட்ச வரம்பு',
        searchPlaceholder: '94+ பட்டாசுகளைத் தேடுக (பூந்தொட்டி, சக்கரம், 12 ஷாட், கிஃப்ட் பாக்ஸ்)...',
        viewCards: 'கார்டுகள்',
        viewRateSheet: 'விலைப்பட்டியல்',
        catAll: 'அனைத்து பட்டாசுகள்',
        catFlowerPots: 'பூந்தொட்டி',
        catGroundChakkars: 'தரைச்சக்கரம்',
        catSoundCrackers: 'ஒலி பட்டாசுகள்',
        catBombs: 'வெடிகள் / பாம்',
        catRockets: 'ராக்கெட்டுகள்',
        catSkyShots: 'வானவேடிக்கை ஷாட்ஸ்',
        catSparklers: 'கம்பி மத்தாப்பு',
        catFancyItems: 'ஃபேன்ஸி ரகங்கள்',
        catGarlands: 'சரவெடி / லார்',
        catGiftBoxes: 'கிஃப்ட் பாக்ஸ்கள்',
        saveDiscount: '60% சேமிப்பு',
        subtotalText: 'கூட்டுத்தொகை',
        mrpText: 'சில்லறை MRP',
        wholesaleRateText: 'மொத்த விலை',
        quantityText: 'எண்ணிக்கை',
        itemsText: 'பொருட்கள்',
        itemText: 'பொருள்',
        wholesaleTotalText: 'மொத்த விலை:',
        saveText: 'சேமிப்பு',
        viewQuotationBtn: 'விலைப்பட்டியல் காண்க & வாட்ஸ்அப்',
        sivakasiSuper: 'பிரணவ் பட்டாசுகள் • சிவகாசி',
        estQuotationHeading: 'மதிப்பிடப்பட்ட விலைப்பட்டியல்',
        selectedCrackers: 'தேர்ந்தெடுக்கப்பட்ட பட்டாசுகள்',
        clearAllBtn: 'அனைத்தையும் நீக்கு',
        totalSelected: 'தேர்ந்தெடுக்கப்பட்ட பொருட்கள்:',
        estRetailMrp: 'மதிப்பிடப்பட்ட சில்லறை MRP:',
        estWholesaleTotal: 'மதிப்பிடப்பட்ட மொத்த விலை:',
        customerDetailsHeader: 'வாடிக்கையாளர் & முகவரி விவரங்கள்',
        labelName: 'முழு பெயர் *',
        labelPhone: 'வாட்ஸ்அப் / மொபைல் எண் *',
        labelAddress: 'டெலிவரி முகவரி *',
        labelCity: 'ஊர் / நகரம் *',
        labelState: 'மாநிலம் *',
        labelPincode: 'அஞ்சல் குறியீடு (PIN) *',
        labelNotes: 'டெலிவரி குறிப்புகள் (விருப்பத்தேர்வு)',
        placeholderName: 'உங்கள் முழு பெயரை உள்ளிடவும்',
        placeholderPhone: '10 இலக்க மொபைல் எண்',
        placeholderAddress: 'வீட்டு எண், தெரு, பகுதி',
        placeholderCity: 'நகரம்',
        placeholderState: 'தமிழ்நாடு',
        placeholderPincode: '6 இலக்க அஞ்சல் குறியீடு',
        placeholderNotes: 'எ.கா. விருப்பமான டிரான்ஸ்போர்ட், நேரம்',
        legalDisclaimer: '⚠️ சட்ட அறிவிப்பு: இந்திய உச்ச நீதிமன்றம் மற்றும் CSIR-NEERI பசுமை பட்டாசு வழிகாட்டுதல்களின்படி, இந்த தளம் டிஜிட்டல் விலை மதிப்பீட்டுக் கருவியாக செயல்படுகிறது. பொருட்கள் உரிமம் பெற்ற சிவகாசி உற்பத்தியாளர்களிடமிருந்து நேரடியாக வழங்கப்படுகின்றன.',
        btnSendWhatsapp: 'ஆர்டரை வாட்ஸ்அப்பில் அனுப்பவும்',
        reqPreparedTitle: 'விலைப்பட்டியல் தயார்!',
        reqPreparedRef: 'விலைப்பட்டியல் குறிப்பு எண்:',
        reqPreparedMsg: 'உங்கள் மதிப்பீடு வாட்ஸ்அப்பில் திறக்கப்பட்டுள்ளது. எங்கள் சிவகாசி அலுவலகத்திற்கு அனுப்ப வாட்ஸ்அப்பில் Send பொத்தானை அழுத்தவும்.',
        continueBrowsing: 'தொடர்ந்து பார்க்கவும்',
        trackTitle: 'விலைப்பட்டியல் கண்காணிக்க',
        trackPlaceholder: 'குறிப்பு எண் (PCQ-...) அல்லது மொபைல் எண்ணை உள்ளிடவும்',
        trackBtn: 'கண்காணி',
        footerDesk: 'வாட்ஸ்அப் சிவகாசி மையம்',
        footerCall: 'அழைக்க +91 77085 32334',
        footerTrack: 'விலைப்பட்டியல் கண்காணிக்க',
        footerAdmin: 'நிர்வாக உள்நுழைவு',
        footerCopyright: '© 2026 பிரணவ் பட்டாசுகள், சிவகாசி. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
        emptySearchTitle: 'பொருட்கள் எதுவும் கிடைக்கவில்லை',
        emptySearchDesc: 'பூந்தொட்டி, சக்கரம், கம்பி மத்தாப்பு அல்லது கிஃப்ட் பாக்ஸ் எனத் தேடவும்.',
        clearSearchBtn: 'தேடலை அழிக்கவும்',
        showAllBtn: 'அனைத்து பட்டாசுகளையும் காட்டு'
    },

    hi: {
        announcementBadge: '💥 दिवाली 2026',
        announcementText: 'शिवकाशी डायरेक्ट फैक्ट्री थोक भाव • 70% तक भारी छूट • सुरक्षित ऑल-इंडिया डिलीवरी',
        announcementPhone: '📞 शिवकाशी हेल्पडेस्क: +91 77085 32334',
        brandSub: 'शिवकाशी डायरेक्ट थोक पटाखे',
        btnWhatsApp: 'व्हाट्सएप',
        btnCall: 'कॉल करें',
        btnQuotation: 'कोटेशन',
        trustDirectFactory: 'डायरेक्ट शिवकाशी फैक्ट्री',
        trustDirectFactorySub: 'कोई बिचौलिया नहीं',
        trustGreen: 'CSIR-NEERI ग्रीन पटाखे',
        trustGreenSub: 'प्रमाणित पर्यावरण अनुकूल',
        trustBrands: 'असली ब्रांड्स',
        trustBrandsSub: '100% Genuine Sivakasi',
        trustTransport: 'सुरक्षित ट्रांसपोर्ट',
        trustTransportSub: 'पूरे भारत में सुरक्षित डिलीवरी',
        diwaliSaleLive: '🔥 दिवाली 2026 फैक्ट्री सेल लाइव',
        diwaliHeroTitle: 'शिवकाशी के पटाखे डायरेक्ट फैक्ट्री थोक भाव पर',
        diwaliHeroDesc: 'पटाखे चुनें, लाइव अनुमानित बचत देखें और 30 सेकंड में व्हाट्सएप पर अपनी आवश्यकता भेजें।',
        statVarieties: 'किस्में',
        statFactoryOff: 'फैक्ट्री छूट',
        statMinLimit: 'न्यूनतम सीमा',
        searchPlaceholder: '94+ पटाखे खोजें (अनार, चक्र, 12 शॉट, गिफ्ट बॉक्स)...',
        viewCards: 'कार्ड्स',
        viewRateSheet: 'रेट शीट',
        catAll: 'सभी पटाखे',
        catFlowerPots: 'अनार / फूलझड़ी',
        catGroundChakkars: 'जमीनी चकरी',
        catSoundCrackers: 'आवाज़ वाले पटाखे',
        catBombs: 'बम पटाखे',
        catRockets: 'रॉकेट्स',
        catSkyShots: 'आसमानी स्काई शॉट्स',
        catSparklers: 'फुलझड़ियां',
        catFancyItems: 'फैंसी आइटम्स',
        catGarlands: 'लड़ / माला',
        catGiftBoxes: 'गिफ्ट बॉक्सेस',
        saveDiscount: '60% बचत',
        subtotalText: 'उप-योग',
        mrpText: 'खुदरा MRP',
        wholesaleRateText: 'थोक भाव',
        quantityText: 'मात्रा',
        itemsText: 'आइटम्स',
        itemText: 'आइटम',
        wholesaleTotalText: 'थोक कुल योग:',
        saveText: 'बचत',
        viewQuotationBtn: 'कोटेशन देखें और व्हाट्सएप करें',
        sivakasiSuper: 'प्रणव क्रैकर्स • शिवकाशी',
        estQuotationHeading: 'अनुमानित कोटेशन',
        selectedCrackers: 'चुने गए पटाखे',
        clearAllBtn: 'सब हटाएं',
        totalSelected: 'कुल चुने गए आइटम्स:',
        estRetailMrp: 'अनुमानित खुदरा MRP:',
        estWholesaleTotal: 'अनुमानित थोक कुल:',
        customerDetailsHeader: 'ग्राहक और डिलीवरी विवरण',
        labelName: 'पूरा नाम *',
        labelPhone: 'व्हाट्सएप / मोबाइल नंबर *',
        labelAddress: 'डिलीवरी का पता *',
        labelCity: 'शहर / कस्बा *',
        labelState: 'राज्य *',
        labelPincode: 'पिन कोड *',
        labelNotes: 'अतिरिक्त निर्देश (वैकल्पिक)',
        placeholderName: 'अपना पूरा नाम दर्ज करें',
        placeholderPhone: '10 अंकों का मोबाइल नंबर',
        placeholderAddress: 'मकान नं., सड़क, क्षेत्र',
        placeholderCity: 'शहर',
        placeholderState: 'तमिलनाडु',
        placeholderPincode: '6 अंकों का पिन कोड',
        placeholderNotes: 'उदा. पसंदीदा ट्रांसपोर्ट, डिलीवरी का समय',
        legalDisclaimer: '⚠️ कानूनी सूचना: सुप्रीम कोर्ट और CSIR-NEERI के ग्रीन पटाखों के नियमों के अनुसार यह मंच डिजिटल मूल्य अनुमान उपकरण है। उत्पाद सीधे लाइसेंस प्राप्त निर्माताओं द्वारा भेजे जाते हैं।',
        btnSendWhatsapp: 'व्हाट्सएप पर ऑर्डर भेजें',
        reqPreparedTitle: 'आवश्यकता तैयार है!',
        reqPreparedRef: 'कोटेशन संदर्भ संख्या:',
        reqPreparedMsg: 'आपका अनुमानित कोटेशन व्हाट्सएप में तैयार हो गया है। कृपया हमारे शिवकाशी डेस्क को भेजने के लिए व्हाट्सएप में Send दबाएं।',
        continueBrowsing: 'और पटाखे देखें',
        trackTitle: 'कोटेशन ट्रैक करें',
        trackPlaceholder: 'कोटेशन आईडी (PCQ-...) या फोन नंबर दर्ज करें',
        trackBtn: 'ट्रैक करें',
        footerDesk: 'व्हाट्सएप शिवकाशी डेस्क',
        footerCall: 'कॉल +91 77085 32334',
        footerTrack: 'कोटेशन ट्रैक करें',
        footerAdmin: 'एडमिन लॉगिन',
        footerCopyright: '© 2026 प्रणव क्रैकर्स, शिवकाशी। सर्वाधिकार सुरक्षित।',
        emptySearchTitle: 'कोई पटाखा नहीं मिला',
        emptySearchDesc: 'अनार, चक्र, फुलझड़ी या गिफ्ट बॉक्स जैसे लोकप्रिय नाम खोजें।',
        clearSearchBtn: 'खोज साफ़ करें',
        showAllBtn: 'सभी पटाखे दिखाएं'
    },

    te: {
        announcementBadge: '💥 దీపావళి 2026',
        announcementText: 'శివకాశి ప్రత్యక్ష ఫ్యాక్టరీ హోల్‌సేల్ ధరలు • 70% వరకు తగ్గింపు • ఆల్-ఇండియా సురక్షిత డెలివరీ',
        announcementPhone: '📞 శివకాశి డెస్క్: +91 77085 32334',
        brandSub: 'శివకాశి ప్రత్యక్ష హోల్‌సేల్ బాణసంచా',
        btnWhatsApp: 'వాట్సాప్',
        btnCall: 'కాల్ చేయండి',
        btnQuotation: 'కొటేషన్',
        trustDirectFactory: 'డైరెక్ట్ శివకాశి ఫ్యాక్టరీ',
        trustDirectFactorySub: 'మధ్యవర్తుల కమీషన్ లేదు',
        trustGreen: 'CSIR-NEERI గ్రీన్ క్రాకర్స్',
        trustGreenSub: 'పర్యావరణ అనుకూల ధృవీకరణ',
        trustBrands: 'అసలైన బ్రాండ్లు',
        trustBrandsSub: '100% Genuine Sivakasi',
        trustTransport: 'సురక్షిత రవాణా',
        trustTransportSub: 'భారతదేశం అంతటా సురక్షిత డెలివరీ',
        diwaliSaleLive: '🔥 దీపావళి 2026 ఫ్యాక్టరీ సేల్ ప్రారంభం',
        diwaliHeroTitle: 'శివకాశి బాణసంచా ఫ్యాక్టరీ హోల్‌సేల్ ధరలకే',
        diwaliHeroDesc: 'బాణసంచా ఎంచుకోండి, ప్రత్యక్ష తగ్గింపును చూడండి మరియు 30 సెకన్లలో వాట్సాప్‌లో పంపండి.',
        statVarieties: 'రకాలు',
        statFactoryOff: 'తగ్గింపు',
        statMinLimit: 'కనిష్ట పరిమితి',
        searchPlaceholder: '94+ బాణసంచా వెతకండి (చిచ్చుబుడ్లు, భూచక్రాలు, 12 షాట్లు, గిఫ్ట్ బాక్స్)...',
        viewCards: 'కార్డులు',
        viewRateSheet: 'రేట్ షీట్',
        catAll: 'అన్ని బాణసంచా',
        catFlowerPots: 'చిచ్చుబుడ్లు',
        catGroundChakkars: 'భూచక్రాలు',
        catSoundCrackers: 'శబ్ద టపాసులు',
        catBombs: 'బాంబులు',
        catRockets: 'రాకెట్లు',
        catSkyShots: 'స్కై షాట్స్',
        catSparklers: 'మతాబులు',
        catFancyItems: 'ఫ్యాన్సీ రకాలు',
        catGarlands: 'లడ్డీలు / మాలలు',
        catGiftBoxes: 'గిఫ్ట్ బాక్సులు',
        saveDiscount: '60% ఆదా',
        subtotalText: 'సబ్‌టోటల్',
        mrpText: 'రిటైల్ MRP',
        wholesaleRateText: 'హోల్‌సేల్ ధర',
        quantityText: 'పరిమాణం',
        itemsText: 'వస్తువులు',
        itemText: 'వస్తువు',
        wholesaleTotalText: 'హోల్‌సేల్ మొత్తం:',
        saveText: 'ఆదా',
        viewQuotationBtn: 'కొటేషన్ చూడండి & వాట్సాప్',
        sivakasiSuper: 'ప్రణవ్ క్రాకర్స్ • శివకాశి',
        estQuotationHeading: 'అంచనా కొటేషన్',
        selectedCrackers: 'ఎంచుకున్న బాణసంచా',
        clearAllBtn: 'అన్నీ తొలగించు',
        totalSelected: 'ఎంచుకున్న వస్తువులు:',
        estRetailMrp: 'అంచనా రిటైల్ MRP:',
        estWholesaleTotal: 'అంచనా హోల్‌సేల్ మొత్తం:',
        customerDetailsHeader: 'కస్టమర్ & డెలివరీ వివరాలు',
        labelName: 'పూర్తి పేరు *',
        labelPhone: 'వాట్సాప్ / మొబైల్ నంబర్ *',
        labelAddress: 'డెలివరీ చిరునామా *',
        labelCity: 'పట్టణం / నగరం *',
        labelState: 'రాష్ట్రం *',
        labelPincode: 'పిన్ కోడ్ *',
        labelNotes: 'డెలివరీ సూచనలు (ఐచ్ఛికం)',
        placeholderName: 'మీ పూర్తి పేరును నమోదు చేయండి',
        placeholderPhone: '10 అంకెల మొబైల్ నంబర్',
        placeholderAddress: 'ఇంటి నం., వీధి, ప్రాంతం',
        placeholderCity: 'నగరం',
        placeholderState: 'తమిళనాడు',
        placeholderPincode: '6 అంకెల పిన్ కోడ్',
        placeholderNotes: 'ఉదా. రవాణా సేవ, సమయం',
        legalDisclaimer: '⚠️ చట్టపరమైన సమాచారం: సుప్రీం కోర్టు మరియు CSIR-NEERI నిబంధనల ప్రకారం ఇది డిజిటల్ ధర అంచనా వేదిక. ఉత్పత్తులు లైసెన్స్ పొందిన తయారీదారుల నుండి నేరుగా సరఫరా చేయబడతాయి.',
        btnSendWhatsapp: 'ఆర్డర్‌ను వాట్సాప్‌లో పంపండి',
        reqPreparedTitle: 'కొటేషన్ సిద్ధంగా ఉంది!',
        reqPreparedRef: 'కొటేషన్ రిఫరెన్స్:',
        reqPreparedMsg: 'మీ కొటేషన్ వాట్సాప్‌లో సిద్ధమైంది. మా శివకాశి డెస్క్‌కు పంపడానికి వాట్సాప్‌లో Send నొక్కండి.',
        continueBrowsing: 'మరిన్ని చూడండి',
        trackTitle: 'కొటేషన్ ట్రాక్ చేయండి',
        trackPlaceholder: 'కొటేషన్ ఐడీ లేదా ఫోన్ నంబర్ నమోదు చేయండి',
        trackBtn: 'ట్రాక్',
        footerDesk: 'వాట్సాప్ శివకాశి డెస్క్',
        footerCall: 'కాల్ +91 77085 32334',
        footerTrack: 'కొటేషన్ ట్రాక్ చేయండి',
        footerAdmin: 'అడ్మిన్ లాగిన్',
        footerCopyright: '© 2026 ప్రణవ్ క్రాకర్స్, శివకాశి. సర్వహక్కులు ప్రత్యేకించబడినవి.',
        emptySearchTitle: 'ఫలితాలు కనుగొనబడలేదు',
        emptySearchDesc: 'చిచ్చుబుడ్లు, భూచక్రాలు లేదా గిఫ్ట్ బాక్స్ కోసం వెతకండి.',
        clearSearchBtn: 'వెతుకులాట తొలగించు',
        showAllBtn: 'అన్ని బాణసంచా చూపించు'
    },

    ml: {
        announcementBadge: '💥 ദീപാവലി 2026',
        announcementText: 'ശിവകാശി ഡയറക്ട് ഫാക്ടറി മൊത്തവില • 70% വരെ വിലക്കിഴിവ് • അഖിലേന്ത്യാ സുരക്ഷിത ഡെലിവറി',
        announcementPhone: '📞 ശിവകാശി ഹെൽപ്പ്ഡെസ്ക്: +91 77085 32334',
        brandSub: 'ശിവകാശി ഡയറക്ട് മൊത്തവ്യാപാര പടക്കങ്ങൾ',
        btnWhatsApp: 'വാട്സാപ്പ്',
        btnCall: 'വിളിക്കുക',
        btnQuotation: 'ക്വട്ടേഷൻ',
        trustDirectFactory: 'ഡയറക്ട് ശിവകാശി ഫാക്ടറി',
        trustDirectFactorySub: 'ഇടനിലക്കാരുടെ ലാഭമില്ല',
        trustGreen: 'CSIR-NEERI ഗ്രീൻ പടക്കങ്ങൾ',
        trustGreenSub: 'പരിസ്ഥിതി സൗഹൃദ സർട്ടിഫിക്കേഷൻ',
        trustBrands: 'യഥാർത്ഥ ബ്രാൻഡുകൾ',
        trustBrandsSub: '100% Genuine Sivakasi',
        trustTransport: 'സുരക്ഷിത ഗതാഗതം',
        trustTransportSub: 'ഇന്ത്യയിലുടനീളം സുരക്ഷിത ഡെലിവറി',
        diwaliSaleLive: '🔥 ദീപാവലി 2026 ഫാക്ടറി സെയിൽ ആരംഭിച്ചു',
        diwaliHeroTitle: 'ശിവകാശി പടക്കങ്ങൾ ഫാക്ടറി മൊത്തവിലയിൽ',
        diwaliHeroDesc: 'പടക്കങ്ങൾ തിരഞ്ഞെടുക്കൂ, തത്സമയ വിലക്കിഴിവ് കാണൂ, 30 സെക്കൻഡിനുള്ളിൽ വാട്സാപ്പിൽ ഓർഡർ അയക്കൂ.',
        statVarieties: 'ഇനങ്ങൾ',
        statFactoryOff: 'വിലക്കിഴിവ്',
        statMinLimit: 'കുറഞ്ഞ പരിധി',
        searchPlaceholder: '94+ പടക്കങ്ങൾ തിരയൂ (പൂക്കുറ്റി, ചക്രം, 12 ഷോട്ട്, ഗിഫ്റ്റ് ബോക്സ്)...',
        viewCards: 'കാർഡുകൾ',
        viewRateSheet: 'റേറ്റ് ഷീറ്റ്',
        catAll: 'എല്ലാ പടക്കങ്ങളും',
        catFlowerPots: 'പൂക്കുറ്റികൾ',
        catGroundChakkars: 'നിലച്ചക്രങ്ങൾ',
        catSoundCrackers: 'ശബ്ദ പടക്കങ്ങൾ',
        catBombs: 'ബോംബുകൾ',
        catRockets: 'റോക്കറ്റുകൾ',
        catSkyShots: 'സ്കൈ ഷോട്ടുകൾ',
        catSparklers: 'മത്താപ്പുകൾ',
        catFancyItems: 'ഫാൻസി ഇനങ്ങൾ',
        catGarlands: 'മാല പടക്കങ്ങൾ',
        catGiftBoxes: 'ഗിഫ്റ്റ് ബോക്സുകൾ',
        saveDiscount: '60% ലാഭം',
        subtotalText: 'തുക',
        mrpText: 'റീട്ടെയിൽ MRP',
        wholesaleRateText: 'മൊത്തവില',
        quantityText: 'എണ്ണം',
        itemsText: 'ഇനങ്ങൾ',
        itemText: 'ഇനം',
        wholesaleTotalText: 'ആകെ മൊത്തവില:',
        saveText: 'ലാഭം',
        viewQuotationBtn: 'ക്വട്ടേഷൻ കാണുക & വാട്സാപ്പ്',
        sivakasiSuper: 'പ്രണവ് ക്രാക്കേഴ്സ് • ശിവകാശി',
        estQuotationHeading: 'എസ്റ്റിമേറ്റ് ക്വട്ടേഷൻ',
        selectedCrackers: 'തിരഞ്ഞെടുത്ത പടക്കങ്ങൾ',
        clearAllBtn: 'എല്ലാം നീക്കുക',
        totalSelected: 'ആകെ തിരഞ്ഞെടുത്തവ:',
        estRetailMrp: 'എസ്റ്റിമേറ്റ് റീട്ടെയിൽ MRP:',
        estWholesaleTotal: 'എസ്റ്റിമേറ്റ് ആകെ തുക:',
        customerDetailsHeader: 'ഉപഭോക്തൃ വിലാസ വിവരങ്ങൾ',
        labelName: 'പൂർണ്ണ പേര് *',
        labelPhone: 'വാട്സാപ്പ് / മൊബൈൽ നമ്പർ *',
        labelAddress: 'ഡെലിവറി വിലാസം *',
        labelCity: 'സ്ഥലം / നഗരം *',
        labelState: 'സംസ്ഥാനം *',
        labelPincode: 'പിൻ കോഡ് *',
        labelNotes: 'പ്രത്യേക നിർദ്ദേശങ്ങൾ (ഓപ്ഷണൽ)',
        placeholderName: 'നിങ്ങളുടെ പേര് നൽകുക',
        placeholderPhone: '10 അക്ക മൊബൈൽ നമ്പർ',
        placeholderAddress: 'വീട്ടുപേര്, റോഡ്, പ്രദേശം',
        placeholderCity: 'നഗരം',
        placeholderState: 'തമിഴ്നാട്',
        placeholderPincode: '6 അക്ക പിൻ കോഡ്',
        placeholderNotes: 'ഉദാ: ട്രാൻസ്പോർട്ട് നിർദ്ദേശങ്ങൾ',
        legalDisclaimer: '⚠️ നിയമപരമായ അറിയിപ്പ്: സുപ്രീം കോടതി, CSIR-NEERI മാർഗ്ഗനിർദ്ദേശങ്ങൾ പ്രകാരം പ്രവർത്തിക്കുന്ന ഡിജിറ്റൽ എസ്റ്റിമേഷൻ ടൂളാണിത്.',
        btnSendWhatsapp: 'ഓർഡർ വാട്ട്‌സ്ആപ്പിൽ അയക്കുക',
        reqPreparedTitle: 'ക്വട്ടേഷൻ തയ്യാർ!',
        reqPreparedRef: 'ക്വട്ടേഷൻ റഫറൻസ്:',
        reqPreparedMsg: 'നിങ്ങളുടെ എസ്റ്റിമേറ്റ് വാട്സാപ്പിൽ തയ്യാറായിട്ടുണ്ട്. ശിവകാശി ഡെസ്കിലേക്ക് അയക്കാൻ വാട്സാപ്പിൽ Send അമർത്തുക.',
        continueBrowsing: 'തുടർന്നും കാണുക',
        trackTitle: 'ക്വട്ടേഷൻ ട്രാക്ക് ചെയ്യുക',
        trackPlaceholder: 'റഫറൻസ് ഐഡിയോ ഫോൺ നമ്പറോ നൽകുക',
        trackBtn: 'ട്രാക്ക്',
        footerDesk: 'വാട്സാപ്പ് ശിവകാശി ഡെസ്ക്',
        footerCall: 'വിളിക്കുക +91 77085 32334',
        footerTrack: 'ക്വട്ടേഷൻ ട്രാക്ക് ചെയ്യുക',
        footerAdmin: 'അഡ്മിൻ ലോഗിൻ',
        footerCopyright: '© 2026 പ്രണവ് ക്രാക്കേഴ്സ്, ശിവകാശി. എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.',
        emptySearchTitle: 'പടക്കങ്ങൾ ഒന്നും കണ്ടെത്താനായില്ല',
        emptySearchDesc: 'പൂക്കുറ്റി, ചക്രം, മത്താപ്പ് അല്ലെങ്കിൽ ഗിഫ്റ്റ് ബോക്സ് എന്ന് തിരയുക.',
        clearSearchBtn: 'തിരച്ചിൽ മാറ്റുക',
        showAllBtn: 'എല്ലാ പടക്കങ്ങളും കാണിക്കുക'
    },

    kn: {
        announcementBadge: '💥 ದೀಪಾವಳಿ 2026',
        announcementText: 'ಶಿವಕಾಶಿ ನೇರ ಕಾರ್ಖಾನೆ ಸಗಟು ದರಗಳು • 70% ವರೆಗೆ ಭರ್ಜರಿ ರಿಯಾಯಿತಿ • ಭಾರತದಾದ್ಯಂತ ಸುರಕ್ಷಿತ ಡೆಲಿವರಿ',
        announcementPhone: '📞 ಶಿವಕಾಶಿ ಡೆಸ್ಕ್: +91 77085 32334',
        brandSub: 'ಶಿವಕಾಶಿ ನೇರ ಸಗಟು ಪಟಾಕಿಗಳು',
        btnWhatsApp: 'ವಾಟ್ಸಾಪ್',
        btnCall: 'ಕರೆ ಮಾಡಿ',
        btnQuotation: 'ಕೊಟೇಶನ್',
        trustDirectFactory: 'ನೇರ ಶಿವಕಾಶಿ ಕಾರ್ಖಾನೆ',
        trustDirectFactorySub: 'ಮಧ್ಯವರ್ತಿಗಳಿಲ್ಲ',
        trustGreen: 'CSIR-NEERI ಹಸಿರು ಪಟಾಕಿ',
        trustGreenSub: 'ಪರಿಸರ ಸ್ನೇಹಿ ಪ್ರಮಾಣೀಕೃತ',
        trustBrands: 'ಅಸಲಿ ಬ್ರ್ಯಾಂಡ್‌ಗಳು',
        trustBrandsSub: '100% Genuine Sivakasi',
        trustTransport: 'ಸುರಕ್ಷಿತ ಸಾರಿಗೆ',
        trustTransportSub: 'ಭಾರತದಾದ್ಯಂತ ನೇರ ಡೆಲಿವರಿ',
        diwaliSaleLive: '🔥 ದೀಪಾವಳಿ 2026 ಫ್ಯಾಕ್ಟರಿ ಸೇಲ್ ಲೈವ್',
        diwaliHeroTitle: 'ಶಿವಕಾಶಿ ಪಟಾಕಿಗಳು ಕಾರ್ಖಾನೆ ಸಗಟು ದರದಲ್ಲಿ',
        diwaliHeroDesc: 'ಪಟಾಕಿಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ, ಲೈವ್ ರಿಯಾಯಿತಿ ನೋಡಿ ಮತ್ತು 30 ಸೆಕೆಂಡುಗಳಲ್ಲಿ ವಾಟ್ಸಾಪ್ ಮೂಲಕ ಕಳುಹಿಸಿ.',
        statVarieties: 'ವಿಧಗಳು',
        statFactoryOff: 'ರಿಯಾಯಿತಿ',
        statMinLimit: 'ಕನಿಷ್ಠ ಮಿತಿ',
        searchPlaceholder: '94+ ಪಟಾಕಿ ಹುಡುಕಿ (ಹೂಕುಂಡ, ನೆಲಚಕ್ರ, 12 ಶಾಟ್, ಗಿಫ್ಟ್ ಬಾಕ್ಸ್)...',
        viewCards: 'ಕಾರ್ಡ್‌ಗಳು',
        viewRateSheet: 'ದರ ಪಟ್ಟಿ',
        catAll: 'ಎಲ್ಲಾ ಪಟಾಕಿಗಳು',
        catFlowerPots: 'ಹೂಕುಂಡಗಳು',
        catGroundChakkars: 'ನೆಲಚಕ್ರಗಳು',
        catSoundCrackers: 'ಶಬ್ದದ ಪಟಾಕಿ',
        catBombs: 'ಬಾಂಬ್‌ಗಳು',
        catRockets: 'ರಾಕೆಟ್‌ಗಳು',
        catSkyShots: 'ಸ್ಕೈ ಶಾಟ್ಸ್',
        catSparklers: 'ಕಡ್ಡಿ ಮത്താಪು',
        catFancyItems: 'ಫ್ಯಾನ್ಸಿ ಐಟಂಗಳು',
        catGarlands: 'ಸರಪಳಿ ಪಟಾಕಿ',
        catGiftBoxes: 'ಗಿಫ್ಟ್ ಬಾಕ್ಸ್‌ಗಳು',
        saveDiscount: '60% ಉಳಿತಾಯ',
        subtotalText: 'ಒಟ್ಟು ಮೊತ್ತ',
        mrpText: 'ಚಿಲ್ಲರೆ MRP',
        wholesaleRateText: 'ಸಗಟು ದರ',
        quantityText: 'ಪ್ರಮಾಣ',
        itemsText: 'ಐಟಂಗಳು',
        itemText: 'ಐಟಂ',
        wholesaleTotalText: 'ಸಗಟು ಮೊತ್ತ:',
        saveText: 'ಉಳಿತಾಯ',
        viewQuotationBtn: 'ಕೊಟೇಶನ್ ನೋಡಿ ಮತ್ತು ವಾಟ್ಸಾಪ್ ಮಾಡಿ',
        sivakasiSuper: 'ಪ್ರಣವ್ ಕ್ರ್ಯಾಕರ್ಸ್ • ಶಿವಕಾಶಿ',
        estQuotationHeading: 'ಅಂದಾಜು ಕೊಟೇಶನ್',
        selectedCrackers: 'ಆಯ್ಕೆಮಾಡಿದ ಪಟಾಕಿಗಳು',
        clearAllBtn: 'ಎಲ್ಲ ತೆಗೆ',
        totalSelected: 'ಒಟ್ಟು ಆಯ್ಕೆಮಾಡಿದ ಐಟಂಗಳು:',
        estRetailMrp: 'ಅಂದಾಜು ಚಿಲ್ಲರೆ MRP:',
        estWholesaleTotal: 'ಅಂದಾಜು ಸಗಟು ಮೊತ್ತ:',
        customerDetailsHeader: 'ಗ್ರಾಹಕ ಮತ್ತು ಡೆಲಿವರಿ ವಿವರಗಳು',
        labelName: 'ಪೂರ್ಣ ಹೆಸರು *',
        labelPhone: 'ವಾಟ್ಸಾಪ್ / ಮೊಬೈಲ್ ಸಂಖ್ಯೆ *',
        labelAddress: 'ಡೆಲಿವರಿ ವಿಳಾಸ *',
        labelCity: 'ಊರು / ನಗರ *',
        labelState: 'ರಾಜ್ಯ *',
        labelPincode: 'ಪಿನ್ ಕೋಡ್ *',
        labelNotes: 'ವಿಶೇಷ ಸೂಚನೆಗಳು (ಐಚ್ಛಿಕ)',
        placeholderName: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ',
        placeholderPhone: '10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
        placeholderAddress: 'ಮನೆ ನಂ., ರಸ್ತೆ, ಪ್ರದೇಶ',
        placeholderCity: 'ನಗರ',
        placeholderState: 'ತಮಿಳುನಾಡು',
        placeholderPincode: '6 ಅಂಕಿಯ ಪಿನ್ ಕೋಡ್',
        placeholderNotes: 'ಉದಾ. ಸಾರಿಗೆ ವಿವರ, ಸಮಯ',
        legalDisclaimer: '⚠️ ಕಾನೂನು ಮಾಹಿತಿ: ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ಮತ್ತು CSIR-NEERI ಮಾರ್ಗಸೂಚಿಗಳ ಅನ್ವಯ ಇದು ಡಿಜಿಟಲ್ ದರ ಅಂದಾಜು ವೇದಿಕೆಯಾಗಿದೆ.',
        btnSendWhatsapp: 'ಆರ್ಡರ್ ಅನ್ನು ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಕಳುಹಿಸಿ',
        reqPreparedTitle: 'ಕೊಟೇಶನ್ ಸಿದ್ಧವಾಗಿದೆ!',
        reqPreparedRef: 'ಕೊಟೇಶನ್ ರೆಫರೆನ್ಸ್:',
        reqPreparedMsg: 'ನಿಮ್ಮ ಅಂದಾಜು ಕೊಟೇಶನ್ ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಸಿದ್ಧವಾಗಿದೆ. ನಮ್ಮ ಶಿವಕಾಶಿ ಡೆಸ್ಕ್‌ಗೆ ಕಳುಹಿಸಲು Send ಒತ್ತಿರಿ.',
        continueBrowsing: 'ಮುಂದುವರಿಸಿ',
        trackTitle: 'ಕೊಟೇಶನ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
        trackPlaceholder: 'ಕೊಟೇಶನ್ ಐಡಿ ಅಥವಾ ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
        trackBtn: 'ಟ್ರ್ಯಾಕ್',
        footerDesk: 'ವಾಟ್ಸಾಪ್ ಶಿವಕಾಶಿ ಡೆಸ್ಕ್',
        footerCall: 'ಕರೆ +91 77085 32334',
        footerTrack: 'ಕೊಟೇಶನ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
        footerAdmin: 'ಅಡ್ಮಿನ್ ಲಾಗಿನ್',
        footerCopyright: '© 2026 ಪ್ರಣವ್ ಕ್ರ್ಯಾಕರ್ಸ್, ಶಿವಕಾಶಿ. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
        emptySearchTitle: 'ಯಾವುದೇ ಪಟಾಕಿ ಕಂಡುಬಂದಿಲ್ಲ',
        emptySearchDesc: 'ಹೂಕುಂಡ, ನೆಲಚಕ್ರ, ಕಡ್ಡಿ ಮത്താಪು ಅಥವಾ ಗಿಫ್ಟ್ ಬಾಕ್ಸ್ ಎಂದು ಹುಡುಕಿ.',
        clearSearchBtn: 'ಹುಡುಕಾಟ ತೆರವುಗೊಳಿಸಿ',
        showAllBtn: 'ಎಲ್ಲಾ ಪಟಾಕಿಗಳನ್ನು ತೋರಿಸಿ'
    },

    gu: {
        announcementBadge: '💥 દિવાળી 2026',
        announcementText: 'શિવાકાશી ડાયરેક્ટ ફેક્ટરી હોલસેલ ભાવ • 70% સુધી ભારે છૂટ • સુરક્ષિત ઓલ-ઇન્ડિયા ડિલિવરી',
        announcementPhone: '📞 શિવાકાશી ડેસ્ક: +91 77085 32334',
        brandSub: 'શિવાકાશી ડાયરેક્ટ હોલસેલ ફટાકડા',
        btnWhatsApp: 'વોટ્સએપ',
        btnCall: 'કોલ કરો',
        btnQuotation: 'કોટેશન',
        trustDirectFactory: 'ડાયરેક્ટ શિવાકાશી ફેક્ટરી',
        trustDirectFactorySub: 'કોઈ વચેટિયા નથી',
        trustGreen: 'CSIR-NEERI ગ્રીન ફટાકડા',
        trustGreenSub: 'ઇકો-ફ્રેન્ડલી પ્રમાણિત',
        trustBrands: 'અસલી બ્રાન્ડ્સ',
        trustBrandsSub: '100% Genuine Sivakasi',
        trustTransport: 'સુરક્ષિત ટ્રાન્સપોર્ટ',
        trustTransportSub: 'સમગ્ર ભારતમાં સુરક્ષિત ડિલિવરી',
        diwaliSaleLive: '🔥 દિવાળી 2026 ફેક્ટરી સેલ લાઈવ',
        diwaliHeroTitle: 'શિવાકાશીના ફટાકડા ડાયરેક્ટ ફેક્ટરી હોલસેલ ભાવે',
        diwaliHeroDesc: 'ફટાકડા પસંદ કરો, લાઇવ બચત જુઓ અને 30 સેકન્ડમાં વોટ્સએપ પર તમારી જરૂરિયાત મોકલો.',
        statVarieties: 'પ્રકારો',
        statFactoryOff: 'ફેક્ટરી છૂટ',
        statMinLimit: 'ન્યૂનતમ મર્યાદા',
        searchPlaceholder: '94+ ફટાકડા શોધો (કોઠી, ચકરી, 12 શોટ, ગિફ્ટ બોક્સ)...',
        viewCards: 'કાર્ડ્સ',
        viewRateSheet: 'રેટ શીટ',
        catAll: 'બધા ફટાકડા',
        catFlowerPots: 'કોઠી / અનાર',
        catGroundChakkars: 'જમીન ચકરી',
        catSoundCrackers: 'અવાજવાળા ફટાકડા',
        catBombs: 'બોમ્બ',
        catRockets: 'રોકેટ્સ',
        catSkyShots: 'સ્કાય શોટ્સ',
        catSparklers: 'તારામંડળ / ફૂલઝડી',
        catFancyItems: 'ફેન્સી આઇટમ્સ',
        catGarlands: 'લડી / માળા',
        catGiftBoxes: 'ગિફ્ટ બોક્સ',
        saveDiscount: '60% બચત',
        subtotalText: 'પેટા સરવાળો',
        mrpText: 'રિટેલ MRP',
        wholesaleRateText: 'હોલસેલ ભાવ',
        quantityText: 'જથ્થો',
        itemsText: 'આઇટમ્સ',
        itemText: 'આઇટમ',
        wholesaleTotalText: 'હોલસેલ કુલ:',
        saveText: 'બચત',
        viewQuotationBtn: 'કોટેશન જુઓ અને વોટ્સએપ કરો',
        sivakasiSuper: 'પ્રણવ ક્રેકર્સ • શિવાકાશી',
        estQuotationHeading: 'અંદાજિત કોટેશન',
        selectedCrackers: 'પસંદ કરેલા ફટાકડા',
        clearAllBtn: 'બધું સાફ કરો',
        totalSelected: 'કુલ પસંદ કરેલ આઇટમ્સ:',
        estRetailMrp: 'અંદાજિત રિટેલ MRP:',
        estWholesaleTotal: 'અંદાજિત હોલસેલ કુલ:',
        customerDetailsHeader: 'ગ્રાહક અને ડિલિવરી વિગતો',
        labelName: 'પૂરું નામ *',
        labelPhone: 'વોટ્સએપ / મોબાઇલ નંબર *',
        labelAddress: 'ડિલિવરી સરનામું *',
        labelCity: 'શહેર / નગર *',
        labelState: 'રાજ્ય *',
        labelPincode: 'પિન કોડ *',
        labelNotes: 'ખાસ સૂચનાઓ (વૈકલ્પિક)',
        placeholderName: 'તમારું પૂરું નામ દાખલ કરો',
        placeholderPhone: '10 અંકનો મોબાઇલ નંબર',
        placeholderAddress: 'ઘર નં., શેરી, વિસ્તાર',
        placeholderCity: 'શહેર',
        placeholderState: 'તમિલનાડુ',
        placeholderPincode: '6 અંકનો પિન કોડ',
        placeholderNotes: 'દા.ત. ટ્રાન્સપોર્ટ સેવા, સમય',
        legalDisclaimer: '⚠️ કાનૂની સૂચના: સુપ્રીમ કોર્ટ અને CSIR-NEERI ના નિયમો અનુસાર આ એક ડિજિટલ પ્રાઇસ એસ્ટીમેશન ટૂલ છે.',
        btnSendWhatsapp: 'ઓર્ડર વોટ્સએપ પર મોકલો',
        reqPreparedTitle: 'કોટેશન તૈયાર છે!',
        reqPreparedRef: 'કોટેશન સંદર્ભ:',
        reqPreparedMsg: 'તમારું કોટેશન વોટ્સએપમાં તૈયાર થઈ ગયું છે. અમારા શિવાકાશી ડેસ્કને મોકલવા Send બટન દબાવો.',
        continueBrowsing: 'વધુ ફટાકડા જુઓ',
        trackTitle: 'કોટેશન ટ્રેક કરો',
        trackPlaceholder: 'કોટેશન આઈડી અથવા ફોન નંબર દાખલ કરો',
        trackBtn: 'ટ્રેક',
        footerDesk: 'વોટ્સએપ શિવાકાશી ડેસ્ક',
        footerCall: 'કોલ +91 77085 32334',
        footerTrack: 'કોટેશન ટ્રેક કરો',
        footerAdmin: 'એડમિન લૉગિન',
        footerCopyright: '© 2026 પ્રણવ ક્રેકર્સ, શિવાકાશી. સર્વાધિકાર સુરક્ષિત.',
        emptySearchTitle: 'કોઈ ફટાકડા મળ્યા નથી',
        emptySearchDesc: 'કોઠી, ચકરી, ફૂલઝડી કે ગિફ્ટ બોક્સ શોધો.',
        clearSearchBtn: 'શોધ સાફ કરો',
        showAllBtn: 'બધા ફટાકડા બતાવો'
    },

    mr: {
        announcementBadge: '💥 दिवाळी 2026',
        announcementText: 'शिवाकाशी थेट फॅक्टरी घाऊक दर • 70% पर्यंत सवलत • संपूर्ण भारतात सुरक्षित डिलिव्हरी',
        announcementPhone: '📞 शिवाकाशी डेस्क: +91 77085 32334',
        brandSub: 'शिवाकाशी थेट घाऊक फटाके',
        btnWhatsApp: 'व्हॉट्सअ‍ॅप',
        btnCall: 'कॉल करा',
        btnQuotation: 'कोटेशन',
        trustDirectFactory: 'थेट शिवाकाशी फॅक्टरी',
        trustDirectFactorySub: 'मध्यस्थांशिवाय थेट दर',
        trustGreen: 'CSIR-NEERI ग्रीन फटाके',
        trustGreenSub: 'पर्यावरणपूरक प्रमाणित',
        trustBrands: 'अस्सल ब्रँड्स',
        trustBrandsSub: '100% Genuine Sivakasi',
        trustTransport: 'सुरक्षित वाहतूक',
        trustTransportSub: 'भारतात सर्वत्र सुरक्षित पोहोच',
        diwaliSaleLive: '🔥 दिवाळी 2026 फॅक्टरी सेल सुरू',
        diwaliHeroTitle: 'शिवाकाशीचे फटाके थेट फॅक्टरी घाऊक दरात',
        diwaliHeroDesc: 'फटाके निवडा, थेट बचत पाहा आणि 30 सेकंदात व्हॉट्सअ‍ॅपवर मागणी पाठवा.',
        statVarieties: 'प्रकार',
        statFactoryOff: 'फॅक्टरी सूट',
        statMinLimit: 'किमान मर्यादा',
        searchPlaceholder: '94+ फटाके शोधा (अनार, चक्र, 12 शॉट, गिफ्ट बॉक्स)...',
        viewCards: 'कार्ड्स',
        viewRateSheet: 'रेट शीट',
        catAll: 'सर्व फटाके',
        catFlowerPots: 'अनार / कोठी',
        catGroundChakkars: 'भुईचक्र',
        catSoundCrackers: 'आवाजाचे फटाके',
        catBombs: 'बॉम्ब',
        catRockets: 'रॉकेट्स',
        catSkyShots: 'आकाशी शॉट्स',
        catSparklers: 'फुलबाजा',
        catFancyItems: 'फॅन्सी आयटम्स',
        catGarlands: 'माळा / लड',
        catGiftBoxes: 'गिफ्ट बॉक्सेस',
        saveDiscount: '60% बचत',
        subtotalText: 'उप-एकूण',
        mrpText: 'किरकोळ MRP',
        wholesaleRateText: 'घाऊक दर',
        quantityText: 'प्रमाण',
        itemsText: 'आयटम्स',
        itemText: 'आयटम',
        wholesaleTotalText: 'घाऊक एकूण:',
        saveText: 'बचत',
        viewQuotationBtn: 'कोटेशन पाहा आणि व्हॉट्सअ‍ॅप करा',
        sivakasiSuper: 'प्रणव क्रॅकर्स • शिवाकाशी',
        estQuotationHeading: 'अंदाजित कोटेशन',
        selectedCrackers: 'निवडलेले फटाके',
        clearAllBtn: 'सर्व हटवा',
        totalSelected: 'एकूण निवडलेले आयटम्स:',
        estRetailMrp: 'अंदाजित किरकोळ MRP:',
        estWholesaleTotal: 'अंदाजित घाऊक एकूण:',
        customerDetailsHeader: 'ग्राहक आणि डिलिव्हरी तपशील',
        labelName: 'पूर्ण नाव *',
        labelPhone: 'व्हॉट्सअ‍ॅप / मोबाईल नंबर *',
        labelAddress: 'डिलिव्हरी पत्ता *',
        labelCity: 'शहर / गाव *',
        labelState: 'राज्य *',
        labelPincode: 'पिन कोड *',
        labelNotes: 'डिलिव्हरी सूचना (पर्यायी)',
        placeholderName: 'आपले पूर्ण नाव प्रविष्ट करा',
        placeholderPhone: '10 अंकी मोबाईल नंबर',
        placeholderAddress: 'घर क्र., रस्ता, परिसर',
        placeholderCity: 'शहर',
        placeholderState: 'तमिळनाडू',
        placeholderPincode: '6 अंकी पिन कोड',
        placeholderNotes: 'उदा. ट्रान्सपोर्ट सेवा, वेळ',
        legalDisclaimer: '⚠️ कायदेशीर सूचना: सुप्रीम कोर्ट आणि CSIR-NEERI च्या मार्गदर्शक तत्त्वांनुसार हे डिजिटल दर अंदाज साधन आहे.',
        btnSendWhatsapp: 'ऑर्डर व्हॉट्सॲपवर पाठवा',
        reqPreparedTitle: 'कोटेशन तयार झाले!',
        reqPreparedRef: 'कोटेशन संदर्भ:',
        reqPreparedMsg: 'आपले अंदाजित कोटेशन व्हॉट्सअ‍ॅपमध्ये तयार झाले आहे. आमच्या शिवाकाशी डेस्कला पाठवण्यासाठी Send दाबा.',
        continueBrowsing: 'आणखी फटाके पाहा',
        trackTitle: 'कोटेशन ट्रॅक करा',
        trackPlaceholder: 'कोटेशन आयडी किंवा फोन नंबर टाका',
        trackBtn: 'ट्रॅक',
        footerDesk: 'व्हॉट्सअ‍ॅप शिवाकाशी डेस्क',
        footerCall: 'कॉल +91 77085 32334',
        footerTrack: 'कोटेशन ट्रॅक करा',
        footerAdmin: 'अ‍ॅडমিন लॉगिन',
        footerCopyright: '© 2026 प्रणव क्रॅकर्स, शिवाकाशी. सर्व हक्क राखीव.',
        emptySearchTitle: 'कोणतेही फटाके आढळले नाहीत',
        emptySearchDesc: 'अनार, चक्र, फुलबाजा किंवा गिफ्ट बॉक्स शोधा.',
        clearSearchBtn: 'शोध साफ करा',
        showAllBtn: 'सर्व फटाके दाखवा'
    },

    bn: {
        announcementBadge: '💥 দীপাবলি 2026',
        announcementText: 'শিবকাশী ডাইরেক্ট কারখানা পাইকারি দর • 70% পর্যন্ত বিশাল ছাড় • সারা ভারতে নিরাপদ ডেলিভারি',
        announcementPhone: '📞 শিবকাশী হেল্পডেস্ক: +91 77085 32334',
        brandSub: 'শিবকাশী সরাসরি পাইকারি বাজি',
        btnWhatsApp: 'হোয়াটসঅ্যাপ',
        btnCall: 'কল করুন',
        btnQuotation: 'কোটেশন',
        trustDirectFactory: 'সরাসরি শিবকাশী কারখানা',
        trustDirectFactorySub: 'কোনো দালাল নেই',
        trustGreen: 'CSIR-NEERI সবুজ বাজি',
        trustGreenSub: 'পরিবেশ বান্ধব প্রত্যয়িত',
        trustBrands: 'আসল ব্র্যান্ড',
        trustBrandsSub: '100% Genuine Sivakasi',
        trustTransport: 'নিরাপদ পরিবহন',
        trustTransportSub: 'সারা ভারতে নিরাপদ ডেলিভারি',
        diwaliSaleLive: '🔥 দীপাবলি 2026 কারখানা সেল লাইভ',
        diwaliHeroTitle: 'শিবকাশীর বাজি সরাসরি কারখানা পাইকারি দরে',
        diwaliHeroDesc: 'বাজি নির্বাচন করুন, লাইভ সঞ্চয় দেখুন এবং 30 সেকেন্ডে হোয়াটসঅ্যাপে অর্ডার পাঠান।',
        statVarieties: 'প্রকারভেদ',
        statFactoryOff: 'কারখানা ছাড়',
        statMinLimit: 'ন্যূনতম সীমা',
        searchPlaceholder: '94+ বাজি খুঁজুন (তুবড়ি, চরকি, 12 শট, গিফট বক্স)...',
        viewCards: 'কার্ডস',
        viewRateSheet: 'রেট শিট',
        catAll: 'সব বাজি',
        catFlowerPots: 'তুবড়ি / আনার',
        catGroundChakkars: 'মাটি চরকি',
        catSoundCrackers: 'শব্দ বাজি',
        catBombs: 'বোমা বাজি',
        catRockets: 'রকেট',
        catSkyShots: 'আকাশ বাজি / স্কাই শটস',
        catSparklers: 'ফুলঝুরি / তারাবাতি',
        catFancyItems: 'ফ্যান্সি আইটেম',
        catGarlands: 'লড়ি / মালা বাজি',
        catGiftBoxes: 'গিফট বক্স',
        saveDiscount: '60% সাশ্রয়',
        subtotalText: 'মোট মূল্য',
        mrpText: 'খুচরা MRP',
        wholesaleRateText: 'পাইকারি দর',
        quantityText: 'পরিমাণ',
        itemsText: 'আইটেম',
        itemText: 'আইটেম',
        wholesaleTotalText: 'পাইকারি মোট:',
        saveText: 'সাশ্রয়',
        viewQuotationBtn: 'কোটেশন দেখুন এবং হোয়াটসঅ্যাপ করুন',
        sivakasiSuper: 'প্রণব ক্র্যাকার্স • শিবকাশী',
        estQuotationHeading: 'আনুমানিক কোটেশন',
        selectedCrackers: 'নির্বাচিত বাজি',
        clearAllBtn: 'সব মুছুন',
        totalSelected: 'মোট নির্বাচিত আইটেম:',
        estRetailMrp: 'আনুমানিক খুচরা MRP:',
        estWholesaleTotal: 'আনুমানিক পাইকারি মোট:',
        customerDetailsHeader: 'গ্রাহক ও ডেলিভারির বিবরণ',
        labelName: 'পুরো নাম *',
        labelPhone: 'হোয়াটসঅ্যাপ / মোবাইল নম্বর *',
        labelAddress: 'ডেলিভারি ঠিকানা *',
        labelCity: 'শহর / নগর *',
        labelState: 'রাজ্য *',
        labelPincode: 'পিন কোড *',
        labelNotes: 'ডেলিভারি সংক্রান্ত নোট (ঐচ্ছিক)',
        placeholderName: 'আপনার পুরো নাম লিখুন',
        placeholderPhone: '10 সংখ্যার মোবাইল নম্বর',
        placeholderAddress: 'বাড়ি নং, রাস্তা, এলাকা',
        placeholderCity: 'শহর',
        placeholderState: 'তামিলনাড়ু',
        placeholderPincode: '6 সংখ্যার পিন কোড',
        placeholderNotes: 'যেমন: পরিবহন মাধ্যম, সময়',
        legalDisclaimer: '⚠️ আইনি বিজ্ঞপ্তি: সুপ্রিম কোর্ট ও CSIR-NEERI নিয়ম অনুযায়ী এটি একটি ডিজিটাল মূল্য অনুমান সরঞ্জাম।',
        btnSendWhatsapp: 'অর্ডার হোয়াটসঅ্যাপে পাঠান',
        reqPreparedTitle: 'কোটেশন প্রস্তুত!',
        reqPreparedRef: 'কোটেশন রেফারেন্স:',
        reqPreparedMsg: 'আপনার আনুমানিক কোটেশন প্রস্তুত হয়েছে। আমাদের শিবকাশী ডেস্কে পাঠাতে হোয়াটসঅ্যাপে Send চাপুন।',
        continueBrowsing: 'আরও বাজি দেখুন',
        trackTitle: 'কোটেশন ট্র্যাক করুন',
        trackPlaceholder: 'কোটেশন আইডি বা ফোন নম্বর লিখুন',
        trackBtn: 'ট্র্যাক',
        footerDesk: 'হোয়াটসঅ্যাপ শিবকাশী ডেস্ক',
        footerCall: 'কল করুন +91 77085 32334',
        footerTrack: 'কোটেশন ট্র্যাক করুন',
        footerAdmin: 'অ্যাডমিন লগইন',
        footerCopyright: '© 2026 প্রণব ক্র্যাকার্স, শিবকাশী। সর্বস্বত্ব সংরক্ষিত।',
        emptySearchTitle: 'কোনো বাজি পাওয়া যায়নি',
        emptySearchDesc: 'তুবড়ি, চরকি, তারাবাতি বা গিফট বক্সের মতো নাম দিয়ে খুঁজুন।',
        clearSearchBtn: 'অনুসন্ধান মুছুন',
        showAllBtn: 'সব বাজি দেখান'
    }
};

class LanguageManager {
    static getSupportedLanguages() {
        return SUPPORTED_LANGUAGES;
    }

    static getLanguage() {
        if (typeof localStorage === 'undefined') return 'en';
        const key = (typeof STORAGE_KEYS !== 'undefined' && STORAGE_KEYS.LANGUAGE) ? STORAGE_KEYS.LANGUAGE : 'pranav_crackers_language_v4';
        const stored = localStorage.getItem(key) || 'en';
        return TRANSLATIONS[stored] ? stored : 'en';
    }

    static setLanguage(lang) {
        if (!TRANSLATIONS[lang]) lang = 'en';
        if (typeof localStorage !== 'undefined') {
            const key = (typeof STORAGE_KEYS !== 'undefined' && STORAGE_KEYS.LANGUAGE) ? STORAGE_KEYS.LANGUAGE : 'pranav_crackers_language_v4';
            localStorage.setItem(key, lang);
        }
        if (typeof document !== 'undefined') {
            document.documentElement.lang = lang;
            this.applyTranslations();
            this.updateLanguageUI();
        }
        if (typeof window !== 'undefined' && typeof window.dispatchEvent === 'function' && typeof CustomEvent === 'function') {
            window.dispatchEvent(new CustomEvent('languageChanged', { detail: { lang } }));
        }
    }

    static t(key) {
        const lang = this.getLanguage();
        return (TRANSLATIONS[lang] && TRANSLATIONS[lang][key]) || (TRANSLATIONS['en'] && TRANSLATIONS['en'][key]) || key;
    }

    static updateLanguageUI() {
        if (typeof document === 'undefined') return;
        const currentLang = this.getLanguage();

        // Update all language select dropdowns
        document.querySelectorAll('.lang-select-dropdown').forEach(sel => {
            sel.value = currentLang;
        });

        // Update language buttons if any
        document.querySelectorAll('.lang-btn').forEach(btn => {
            const btnLang = btn.getAttribute('data-lang');
            btn.classList.toggle('active', btnLang === currentLang);
        });

        // Update current language label display
        const langObj = SUPPORTED_LANGUAGES.find(l => l.code === currentLang) || SUPPORTED_LANGUAGES[0];
        document.querySelectorAll('.current-lang-name').forEach(el => {
            el.textContent = langObj.nativeName;
        });
    }

    static applyTranslations() {
        if (typeof document === 'undefined') return;
        const lang = this.getLanguage();
        const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;

        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (dict[key]) {
                el.textContent = dict[key];
            }
        });

        document.querySelectorAll('[data-i18n-html]').forEach(el => {
            const key = el.getAttribute('data-i18n-html');
            if (dict[key]) {
                el.innerHTML = dict[key];
            }
        });

        document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
            const key = el.getAttribute('data-i18n-placeholder');
            if (dict[key]) {
                el.setAttribute('placeholder', dict[key]);
            }
        });

        document.querySelectorAll('[data-i18n-title]').forEach(el => {
            const key = el.getAttribute('data-i18n-title');
            if (dict[key]) {
                el.setAttribute('title', dict[key]);
                el.setAttribute('aria-label', dict[key]);
            }
        });
    }

    static init() {
        const lang = this.getLanguage();
        this.setLanguage(lang);
    }
}

// Global window assignments
if (typeof window !== 'undefined') {
    window.SUPPORTED_LANGUAGES = SUPPORTED_LANGUAGES;
    window.TRANSLATIONS = TRANSLATIONS;
    window.LanguageManager = LanguageManager;
}

// Auto-initialize on DOM ready
if (typeof document !== 'undefined') {
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', () => {
            LanguageManager.init();
        });
    } else {
        LanguageManager.init();
    }
}
