services:
  - type: web
    name: pranav-crackers
    runtime: node
    plan: free
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
